### ISSUE TITLE
Sphere line width changes when Line added with specified line width

### ISSUE THREAD

**Issue by drewm1980** [vispy/vispy#1240] opened 2016-06-17 17:24 UTC
If add a sphere to my scene and then add a line with a width, the line width of the sphere changes too. To reproduce: 
1. put this in a script and run it
2. observe thin sphere lines
3. hit any key besides escape and drag in the window to refresh the sphere
4. observe fat lines in sphere mesh

```
import numpy as np
import vispy.scene
from vispy.scene import visuals
from vispy.visuals.transforms import STTransform
import vispy.gloo
import numpy

scene = vispy.scene
canvas = vispy.scene.SceneCanvas(keys='interactive', show=True, fullscreen=False)
view = canvas.central_widget.add_view()

from load_ply import load_ply

sphere = visuals.Sphere(radius=1,
                              method='ico',
                              subdivisions = 3,
                              parent=view.scene,
                              color=[1,1,1,0.05],
                              edge_color=[1,1,1,0.1])

gl_state=['translucent','opaque','additive'][2]
sphere.set_gl_state(gl_state)

view.camera = 'arcball'
view.camera.fov = 0.0 # yields orthorgraphic projection, the default.
view.camera.center = [0,0,0]
view.camera.scale_factor = 2 

pos = numpy.array([[0,0,0],[1,1,1]])

def add_line():
    line = scene.Line(pos=pos,
            color='green',
            method='gl',
            width=8,
            connect='strip',
            parent=view.scene)
    line.antialias=1

@canvas.events.key_press.connect
def on_key_press(event):
    import numpy
    if event.key == 'Escape':
        print 'Exiting annotation GUI normally!'
        return
    add_line() # Makes sphere lines fat too!


if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
```

**Comment by drewm1980** [comment] 2016-06-20 08:27
A temporary workaround is to add a line (of the width you want your sphere's mesh to be) to the scene graph before you add the sphere.

**Comment by drewm1980** [comment] 2016-06-20 08:54
I seems that line width hasn't been added anywhere in the class hierarchy resulting in spheres:

MeshData
MeshVisual
Sphere

I was about to take a crack at adding line width, but I'm not sure at what level of abstraction it should go... MeshData already has line colors, but I was expecting it to only have geometry, with the visual stuff like line width and color coming at the MeshVisual class.

Also, it seems like maybe the line width story isn't even sorted out even for lines:

```
       # Turn on line smooth and/or line width
        if GL:
            if self._parent._antialias:
                GL.glEnable(GL.GL_LINE_SMOOTH)
            else:
                GL.glDisable(GL.GL_LINE_SMOOTH)
            px_scale = self.transforms.pixel_scale
            width = px_scale * self._parent._width
            GL.glLineWidth(max(width, 1.))

        if self._parent._changed['connect']:
            self._connect = self._parent._interpret_connect()
            if isinstance(self._connect, np.ndarray):
                self._connect_ibo.set_data(self._connect)
        if self._connect is None:
            return False
```
But in the documentation, it states:

>         width:
>             The width of the line in px. Line widths > 1px are only
>             guaranteed to work when using 'agg' method.

Is that a typo, and it should say "widths < 1 px" ?

**Comment by drewm1980** [comment] 2016-06-20 10:48
I created a pull request for the doc typo.

For the missing line_width in SphereVisual and MeshVisual, I started working in a feature branch:

https://github.com/drewm1980/vispy/tree/fix_line_width

It's currently broken when the mesh draws because I don't know what I'm doing:

```
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/program.py", line 439, in draw
    raise RuntimeError('Must have at least one attribute')

```

but maybe someone who knows what they're doing can glance at that branch and at least know more quickly what I'm talking about.

I worry that details like the backend, opengl state, anti-aliasing, etc... are starting to propagate around in high level code, and my patch in its current state probably makes the situation worse.

I imagine a mesh being reimplemented as a bunch of lines would be too slow, but maybe meshes and lines should have a shared parent that encapsulates line properties like color and width?

**Comment by Eric89GXL** [comment] 2016-06-20 19:09
I don't know the answer offhand unfortunately. It would take some digging for me to figure it out. I think you're right that there is too much mixing of levels and where attributes are stored going on :(

**Comment by drewm1980** [comment] 2016-06-22 08:23
Ideas are cheap, but here's one for a test function to catch stuff like this:

1. Render a scene containing every primitive with randomized but fixed attributes, and non-overlapping bounding boxes. 
2. Re-render with the objects in varying orders in the scene graph, and make sure the same thing gets rendered.

Alternatively, if you have a way to systematically mess with everything stateful on the gpu, maybe you can set it to two random states and test if the primitive renders the same...

**Comment by kmuehlbauer** [comment] 2017-11-07 15:01
technical duplicate of #1059

**Closed by kmuehlbauer** 2017-11-07 15:01 UTC

**Comment by aviogit** [comment] 2020-01-29 11:07
You solved this bug too well, now there is no way to set line width using OpenGL backend :)
