### ISSUE TITLE
Multiple sequential off screen renderings cause memory leak. 

### ISSUE THREAD

**Issue by SebastianGrans** [vispy/vispy#1819] opened 2020-02-13 09:42 UTC
I am currently constructing a dataset for a machine learning project were I need to some synthetic data from real data. I have the projection matrix, multiple models (.ply) and their transformation matrices. 
So I use VisPy to sequentially render each object using various transformations and save it out as a png file. Each object has 504 different transformations. In total I have to render 10k+ images. 

When I begin rendering these images, I quickly run into memory issues. After rendering only 200 images, the memory consumption was 9 GB+ (and 4 GB of GPU memory).

The rendering script is based on [this](https://github.com/thodan/t-less_toolkit/blob/master/pytless/renderer.py), which is provided by the author who made the dataset which I am now extending. 

Inspired by [this](https://benbernardblog.com/tracking-down-a-freaky-python-memory-leak/) blog post, I tried to track down the leak using ObjGraph. But I can't really figure out whats causing it. 
I've included the graphs of dict, functions and tuples. 
[dotfiles.zip](https://github.com/vispy/vispy/files/4197509/dotfiles.zip)

``` 
 >> objgraph.show_most_common_types(limit=50)
dict                         22825
list                         20649
function                     18916
tuple                        15162
builtin_function_or_method   13904
weakref                      5650
wrapper_descriptor           5408
getset_descriptor            4493
_FuncPtr                     3145
type                         2433
method_descriptor            2086
cell                         1858
member_descriptor            1722
set                          1440
<<I clipped it here>>
```

Here is smaller version of the script which only renders 504 images. After only 10 iterations in the `for vidx, view in enumerate(view_id):` in the `main()` function it consumes 1 GB of RAM and 0.5 GB of GPU RAM.

Would be awesome if someone could help shed some light on this :) 

```python
# Author: Tomas Hodan (hodantom@cmp.felk.cvut.cz)
# Center for Machine Perception, Czech Technical University in Prague

import numpy as np
from vispy import app, gloo

# WARNING: doesn't work with Qt4 (update() does not call on_draw()??)
app.use_app('PyGlet') # Set backend

# Color vertex shader
#-------------------------------------------------------------------------------
_color_vertex_code = """
uniform mat4 u_mv;
uniform mat4 u_mvp;
uniform vec3 u_light_eye_pos;

attribute vec3 a_position;
attribute vec4 a_color;

varying vec4 v_color;
varying vec3 v_eye_pos;
varying vec3 v_L;

void main() {
    gl_Position = u_mvp * vec4(a_position, 1.0);
    v_color = a_color;
    v_eye_pos = (u_mv * vec4(a_position, 1.0)).xyz; // Vertex position in eye coordinates
    v_L = normalize(u_light_eye_pos - v_eye_pos); // Vector to the light
}
"""

# Color fragment shader
#-------------------------------------------------------------------------------
_color_fragment_code = """
uniform float u_light_ambient_w;

varying vec4 v_color;
varying vec3 v_eye_pos;
varying vec3 v_L;

void main() {
    // Face normal in eye coordinates
    vec3 face_normal = normalize(cross(dFdx(v_eye_pos), dFdy(v_eye_pos)));

    float light_diffuse_w = max(dot(normalize(v_L), normalize(face_normal)), 0.0);
    float light_w = u_light_ambient_w + light_diffuse_w;
    if(light_w > 1.0) light_w = 1.0;
    gl_FragColor = light_w * v_color;
}
"""

# Depth vertex shader
# Ref: https://github.com/julienr/vertex_visibility/blob/master/depth.py
#-------------------------------------------------------------------------------
# Getting the depth from the depth buffer in OpenGL is doable, see here:
#   http://web.archive.org/web/20130416194336/http://olivers.posterous.com/linear-depth-in-glsl-for-real
#   http://web.archive.org/web/20130426093607/http://www.songho.ca/opengl/gl_projectionmatrix.html
#   http://stackoverflow.com/a/6657284/116067
# But it is hard to get good precision, as explained in this article:
# http://dev.theomader.com/depth-precision/
#
# Once the vertex is in view space (view * model * v), its depth is simply the
# Z axis. So instead of reading from the depth buffer and undoing the projection
# matrix, we store the Z coord of each vertex in the COLOR buffer and then
# read from the color buffer. OpenGL desktop allows for float32 color buffer
# components.
_depth_vertex_code = """
uniform mat4 u_mv;
uniform mat4 u_mvp;
attribute vec3 a_position;
attribute vec4 a_color;
varying float v_eye_depth;

void main() {
    gl_Position = u_mvp * vec4(a_position, 1.0);
    vec3 v_eye_pos = (u_mv * vec4(a_position, 1.0)).xyz; // Vertex position in eye coordinates

    // OpenGL Z axis goes out of the screen, so depths are negative
    v_eye_depth = -v_eye_pos.z;
}
"""

# Depth fragment shader
#-------------------------------------------------------------------------------
_depth_fragment_code = """
varying float v_eye_depth;

void main() {
    gl_FragColor = vec4(v_eye_depth, 0.0, 0.1, 1.0);
}
"""

# Functions to calculate transformation matrices
# Note that OpenGL expects the matrices to be saved column-wise
# (Ref: http://www.songho.ca/opengl/gl_transform.html)
#-------------------------------------------------------------------------------
# Model-view matrix
def _compute_model_view(model, view):
    return np.dot(model, view)

# Model-view-projection matrix
def _compute_model_view_proj(model, view, proj):
    return np.dot(np.dot(model, view), proj)

# Normal matrix (Ref: http://www.songho.ca/opengl/gl_normaltransform.html)
def _compute_normal_matrix(model, view):
    return np.linalg.inv(np.dot(model, view)).T

# Conversion of Hartley-Zisserman intrinsic matrix to OpenGL projection matrix
#-------------------------------------------------------------------------------
# Ref:
# 1) https://strawlab.org/2011/11/05/augmented-reality-with-OpenGL
# 2) https://github.com/strawlab/opengl-hz/blob/master/src/calib_test_utils.py
def _compute_calib_proj(K, x0, y0, w, h, nc, fc, window_coords='y_down'):
    """
    :param K: Camera matrix.
    :param x0, y0: The camera image origin (normally (0, 0)).
    :param w: Image width.
    :param h: Image height.
    :param nc: Near clipping plane.
    :param fc: Far clipping plane.
    :param window_coords: 'y_up' or 'y_down'.
    :return: OpenGL projection matrix.
    """
    depth = float(fc - nc)
    q = -(fc + nc) / depth
    qn = -2 * (fc * nc) / depth

    # Draw our images upside down, so that all the pixel-based coordinate
    # systems are the same
    if window_coords == 'y_up':
        proj = np.array([
            [2 * K[0, 0] / w, -2 * K[0, 1] / w, (-2 * K[0, 2] + w + 2 * x0) / w, 0],
            [0, -2 * K[1, 1] / h, (-2 * K[1, 2] + h + 2 * y0) / h, 0],
            [0, 0, q, qn], # This row is standard glPerspective and sets near and far planes
            [0, 0, -1, 0]
        ]) # This row is also standard glPerspective

    # Draw the images right side up and modify the projection matrix so that OpenGL
    # will generate window coords that compensate for the flipped image coords
    else:
        assert window_coords == 'y_down'
        proj = np.array([
            [2 * K[0, 0] / w, -2 * K[0, 1] / w, (-2 * K[0, 2] + w + 2 * x0) / w, 0],
            [0, 2 * K[1, 1] / h, (2 * K[1, 2] - h + 2 * y0) / h, 0],
            [0, 0, q, qn], # This row is standard glPerspective and sets near and far planes
            [0, 0, -1, 0]
        ]) # This row is also standard glPerspective
    return proj.T

#-------------------------------------------------------------------------------
class _Canvas(app.Canvas):
    def __init__(self, vertices, faces, size, K, R, t, clip_near, clip_far,
                 bg_color=(0.0, 0.0, 0.0, 0.0), ambient_weight=0.1):

        app.Canvas.__init__(self, show=False, size=size)

        #gloo.gl.use_gl('gl2 debug')

        self.size = size
        self.shape = (self.size[1], self.size[0])
        self.bg_color = bg_color
        self.ambient_weight = ambient_weight

        self.rgb = np.array([])

        # Model matrix
        self.mat_model = np.eye(4, dtype=np.float32) # From object space to world space

        # View matrix (transforming also the coordinate system from OpenCV to
        # OpenGL camera space)
        self.mat_view = np.eye(4, dtype=np.float32) # From world space to eye space
        self.mat_view[:3, :3], self.mat_view[:3, 3] = R, t.squeeze()
        yz_flip = np.eye(4, dtype=np.float32)
        yz_flip[1, 1], yz_flip[2, 2] = -1, -1
        self.mat_view = yz_flip.dot(self.mat_view) # OpenCV to OpenGL camera system
        self.mat_view = self.mat_view.T # OpenGL expects column-wise matrix format

        # Projection matrix
        self.mat_proj = _compute_calib_proj(K, 0, 0, size[0], size[1], clip_near, clip_far)

        # Create buffers
        self.vertex_buffer = gloo.VertexBuffer(vertices)
        self.index_buffer = gloo.IndexBuffer(faces.flatten().astype(np.uint32))

        # We manually draw the hidden canvas
        self.update()

    def on_draw(self, event):
        self.draw_color() # Render color image
        app.quit() # Immediately exit the application after the first drawing

    def draw_color(self):
        program = gloo.Program(_color_vertex_code, _color_fragment_code)
        program.bind(self.vertex_buffer)
        program['u_light_eye_pos'] = [0, 0, 0]
        program['u_light_ambient_w'] = self.ambient_weight
        program['u_mv'] = _compute_model_view(self.mat_model, self.mat_view)
        # program['u_nm'] = compute_normal_matrix(self.model, self.view)
        program['u_mvp'] = _compute_model_view_proj(self.mat_model, self.mat_view, self.mat_proj)

        # Texture where we render the scene
        render_tex = gloo.Texture2D(shape=self.shape + (4,))

        # Frame buffer object
        fbo = gloo.FrameBuffer(render_tex, gloo.RenderBuffer(self.shape))
        with fbo:
            gloo.set_state(depth_test=True)
            gloo.set_state(cull_face=True)
            gloo.set_cull_face('back')  # Back-facing polygons will be culled
            gloo.set_clear_color(self.bg_color)
            gloo.clear(color=True, depth=True)
            gloo.set_viewport(0, 0, *self.size)
            program.draw('triangles', self.index_buffer)

            # Retrieve the contents of the FBO texture
            self.rgb = gloo.read_pixels((0, 0, self.size[0], self.size[1]))[:, :, :3]
            self.rgb = np.copy(self.rgb)

  

#-------------------------------------------------------------------------------
# Ref: https://github.com/vispy/vispy/blob/master/examples/demo/gloo/offscreen.py
def render(model, im_size, K, R, t, clip_near=100, clip_far=2000, bg_color=(0.0, 0.0, 0.0, 0.0),
           ambient_weight=0.1):

    colors = np.ones((model['pts'].shape[0], 4), np.float32) * 0.5
    vertices_type = [('a_position', np.float32, 3),
                     #('a_normal', np.float32, 3),
                     ('a_color', np.float32, 4)]
    vertices = np.array(list(zip(model['pts'], colors)), vertices_type)

    # Rendering
    #---------------------------------------------------------------------------
    c = _Canvas(vertices, model['faces'], im_size, K, R, t, clip_near, clip_far,
                bg_color, ambient_weight)
    
    app.run()

    #---------------------------------------------------------------------------

    out = c.rgb

    c.close()
    return out


def main():
    verbose = 1
    device = 'primesense'
    scene_id = 20
    view_id = list(range(504))
    tless_path = '/home/grans/Documents/t-less_v2'
    model_type = 'cad'

    # A mask for the path to the model file. 
    model_path_mask = os.path.join(tless_path, 'models_' + model_type, 'obj_{:02d}.ply')

    # Scene info contains: 
    #   Intrinsic Camera matrix
    #   Extrinsic camera matrix
    scene_info_path_mask = os.path.join(tless_path, 'test_{}', '{:02d}', 'info.yml')

    # Scene GT contains the transformation matrix of each object in each view.
    scene_gt_path_mask = os.path.join(tless_path, 'test_{}', '{:02d}', 'gt.yml')
   
    scene_info_path = scene_info_path_mask.format(device, scene_id)
    scene_gt_path = scene_gt_path_mask.format(device, scene_id)
    
    scene_info = inout.load_info(scene_info_path)
    scene_gt = inout.load_gt(scene_gt_path)

    # Identify which models are present in the scene, and load
    # their ply files. 
    scene_obj_ids = set()
    for gt in scene_gt[0]:
        scene_obj_ids.add(gt['obj_id'])
    models = {}
    for scene_obj_id in scene_obj_ids:
        model_path = model_path_mask.format(scene_obj_id)
        models[scene_obj_id] = inout.load_ply(model_path)

    # Each scene is photographed from 504 different positions
    for vidx, view in enumerate(view_id):
        if verbose > 0:
            print("Processing view %d (%d/%d)" % (view, vidx+1, len(view_id)))
        view_info = scene_info[view]
        K = view_info['cam_K']
    
        im_size = (720, 540)
        # Render an image of the object visible in each view.
        for midx, gt in enumerate(scene_gt[view]):
            model = models[gt['obj_id']]
            R = gt['cam_R_m2c']
            t = gt['cam_t_m2c']

            # Render the current object
            rendered = render(model, im_size, K, R, t)
            if verbose > 0:
                plt.imshow(rendered)
                plt.show()



if __name__ == "__main__":
    import matplotlib.pyplot as plt
    import inout
    import os
    import sys
    main()
    sys.exit(0)

```

**Comment by djhoese** [comment] 2020-02-13 15:16
Awesome use case! Very interesting. This looks like a lot of low-level code so this is difficult to debug.

Some things that pop out to me are that a `Program` and all other GL objects are made on each iteration in addition to a new Canvas every time. As far as performance goes, if possible, it would be better to reuse as much as possible and change/update the data and parameters that the GPU already knows about. Although it looks like things are getting closed properly, we (the VisPy team) don't have much experience with creating and destroying a ton of Canvases in a single application. There could definitely be something hanging around or objects not getting removed from the GPU properly. You could try playing with Python's `gc` module to force a garbage collection every time.

I also don't have any experience using pyglet. VisPy has been using PyQt5 as the default backend for a little while now so maybe the issues mentioned in the comment at the top about PyQt4 aren't an issue anymore? Not sure that would help any memory leaks. What version of VisPy are you using?

I would also check to see if the Application object is holding on to each of the Canvas objects. If the Canvas objects aren't getting garbage collected then that could be the problem. I still think it would be easier to manage if a single Canvas with a single Program (or multiple Programs if needed) were made and updated. Granted, that would take some major code reworking on your part.

**Comment by codypiersall** [comment] 2020-02-13 15:57
@SebastianGrans I had good luck tracking down memory leaks with objgraph in Vispy.  The thing that was most helpful for me when I was tracking stuff down was using objgraph to create graphs (I think I had it make .svg files) and manually look at the graph on a few different iterations of the loop.  It took a little chunnk of time because I wasn't sure which object to use as the root of the graph, but eventually it was what helped me track some of the leaks down.  objgraph is a very impressive library!  Good luck.

**Comment by SebastianGrans** [comment] 2020-02-14 10:05
@djhoese: Thanks for the input! A classic case of how taking shortcuts ends up biting my ass.

I did some testing with PyQt5, and the results are quite interesting: 
After setting the backend to PyQt5, I was faced with the issue that `on_draw()` wasn't called (just as the original author had commented). The script simply got stuck after `app.run()`. 

I then circumvented this by calling the canvas draw function manually: 
```python 
c.on_draw('bogus')
#app.run()
```
This still renders the scene and the memory leak is gone! :smiley: 
However, if I try this with the Pyglet backend, the memory leak is still present!  
(Regardless, I should probably rewrite the code with your suggestions in mind) 

Regarding versions: VisPy 0.6.4, PyQt5 5.10.1

@codypiersall: Thanks for the advice! I'll keep that in mind.

**Comment by djhoese** [comment] 2020-02-14 14:52
@SebastianGrans Glad you got things working a little better.

Do you think you could file a bug with a simple Qt5 example where you would expect `on_draw` to be called and it doesn't get called? Even better if you can show that it works for Pyglet but not PyQt5. There is probably already an issue on this that got lost in time.

**Comment by djhoese** [comment] 2021-02-27 23:24
It's been a year since the last update on this and there were some suggestions that may improve memory usage. I'm going to close this now. If there are additional memory usage (by anyone) please file a new bug report with a short code sample that reproduces the issue.

**Closed by djhoese** 2021-02-27 23:24 UTC
