### ISSUE TITLE
Add support for 2D x and y arrays in SurfacePlotVisual

### ISSUE THREAD

**Issue by dvsphanindra** [vispy/vispy#1849] opened 2020-04-16 06:34 UTC
As mentioned in the problem [here](https://stackoverflow.com/questions/61175344/how-to-generate-a-paraboloid-surface-and-make-it-respond-to-event), it is currently not possible to create objects with rotational symmentry using the scene.visuals.SurfacePlot() vispy. 
Creating such a surface requires generating grid in cylindrical or spherical coordinates in x and y dimensions. Either the SurfacePlot() should accept the mesh generated by the user or be able to generate such a mesh by accepting inputs from the user.
Is it possible to upgrade the SurfacePlot() function so that axially symmetric objects can be created.
The sample python code for generating such a surface using matplotlib package is also provided in the link above.

1. Is it possible to upgrade the SurfacePlot() function so that axially symmetric objects can be created using vispy.
2. It should also be possible to create hollow surfaces. The sample python code also demonstrates this

**Comment by djhoese** [comment] 2020-04-16 13:17
Thanks for making the issue. I've changed the title since "should" made it sound like something that was intended to work, but doesn't, and is considered a bug. This was designed this way likely because of how much simpler the implementation is.

As for your questions, I don't see any reason why VisPy couldn't be updated to support this. However, in these cases it is usually best if the person behind the coding has a vested interest in the feature. Like I mentioned on stackoverflow I've never actually used the SurfacePlot or isosurface functionality myself and my work doesn't really involve that type of data. Since this feature would be useful to you maybe you could take a look at implementing the functionality?

I'm also going to CC @rougier (sorry for mentioning you everywhere) in case he knows of an existing implementation of surface plots in the form that you want (2D array X, Y, and Z inputs).

**Comment by dvsphanindra** [comment] 2020-04-17 14:05
True. The title is looking better now. Even I am feeling the same after you pointed it out.

I tried modifying the code. It found it difficult as I am new to computer graphics.

**Comment by rougier** [comment] 2020-04-22 13:55
I think it's only a matter of writing the proper transformation inside the vertex shader. I mean, you generate a regular surface plot (X,Y,Z) and in the vertex shader, you can transform these coordinate

**Comment by dvsphanindra** [comment] 2020-04-24 01:36
Sure. I will try. I had already attempted thinking the same. RIght now I am held up with some other work.

**Comment by dvsphanindra** [comment] 2020-05-12 07:34
I have added this support to the SurfacePlotVisual. How do I upload the code? Should I clone and commit with the new feature?

**Comment by kmuehlbauer** [comment] 2020-05-12 07:36
@dvsphanindra Please create a vispy fork (if you haven't already). Push your changes to a dedicated branch at your fork. Create a Pull Request to vispy.

**Comment by djhoese** [comment] 2020-05-12 14:13
@dvsphanindra https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by djhoese** [comment] 2021-03-01 12:50
Well this has been closed for a while due to #1863 but I just didn't set up the github comments properly to auto-close it. Closing now.

**Closed by djhoese** 2021-03-01 12:50 UTC
Labels: component: visuals, type: enhancement
