### ISSUE TITLE
Vispy tries to import PyQt4 after I installed PyQt5

### ISSUE THREAD

**Issue by roman-ku** [vispy/vispy#1309] opened 2017-03-05 19:54 UTC
Hello I am having some problems installing a backend. I had this error:

    RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL']. We recommend PyQt

So I installed PyQt5 from PIP like so:

    pip3 install PyQt5

That installed successfully, now I get this error:

    INFO: Could not import backend "PyQt4":
    No module named 'PyQt4'
    [Finished in 0.7s]

**Comment by fwzhuang** [comment] 2017-03-14 01:29
change scene.SceneCanvas(keys='interactive', app='pyqt4', show=True)  to pyqt5

**Comment by davidh-ssec** [comment] 2017-05-16 22:11
@roman-ku Can you comment on whether @fwzhuang change is what was needed to get this working for you? If it didn't work could you provide the code you are running that is causing this error?

**Comment by roman-ku** [comment] 2017-05-16 22:50
@davidh-ssec 

I don't remember now whether it solved my issue. I think I just went to a different library like matplotlib. I think the line to import the library was the only line I had and it was causing that issue.

**Comment by davidh-ssec** [comment] 2017-05-16 23:12
@roman-ku Ok sounds good. Any idea what operating system you were on when running in to this? I can test this with anaconda on a few systems and if no issues I'll close this.

**Comment by davidh-ssec** [comment] 2017-05-17 00:14
@roman-ku I've looked in to this and this is expected behavior. You didn't mention what code you were running but I've been using the `axes_plots.py` example to test. This example likely resembles how you were creating and running the vispy SceneCanvas. In summary:

    from vispy import app, scene
    canvas = scene.SceneCanvas(keys='interactive', size=(600, 600), show=True)
    if __name__ == '__main__':
        app.run()

Since `app.use_app('pyqt5')` was not called before the `SceneCanvas` was created and the `app` keyword was not passed to `SceneCanvas` as mentioned above, vispy will attempt to load all known backends. It starts with PyQt4, followed by PyQt5, followed by all the other backends until it finds one that it can import. The messages about the failed PyQt4 import are just warnings (if you are not getting warnings let me know) and your code should still continue as expected with PyQt5. If you don't want the warning to show up then I suggest either passing the `app='pyqt5'` keyword to `SceneCanvas` or:

    from vispy import app
    app.use_app('pyqt5')
    from vispy import scene
    ...

...wow this got long.

**Closed by davidh-ssec** 2017-05-17 00:14 UTC

**Comment by iberinsk** [comment] 2017-06-06 12:27
I had the similar issue after reinstalling WinPython and Vispy. I found the following solution: 
1.	Install WinPython with Qt5
2.	Instal Vispy using 
pip install https://github.com/vispy/vispy/archive/master.zip
3.	Open Spyder ->Tools->Preferences->Ipython Console
4.	Open Graphics tab
5.	Change Graphics Backend from Inline to Automattic
6.	Restart Spyder

**Comment by gummyequation** [comment] 2024-03-07 21:29
@iberinsk 
DUDE, thank you so much !!!!
