### ISSUE TITLE
Help! Cannot Import in my Mac

### ISSUE THREAD

**Issue by fortyMiles** [vispy/vispy#1970] opened 2021-01-08 08:37 UTC
### Problem Description 

when I import vispy in Mac:

```
import vispy
```

will occur 

```
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found
```

### Environment 

+ Python 3.8 (if I use python3.6 environment, this problem also exists)
+ MacOS BigSur 11.1

### Priority 

I tried so many ways to solve it. But cannot solve it at all. 

Please help me

**Comment by fortyMiles** [comment] 2021-01-08 08:53
> ### Problem Description
> when I import vispy in Mac:
> 
> ```
> import vispy
> ```
> 
> will occur
> 
> ```
> AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found
> ```
> 
> ### Environment
> * Python 3.8 (if I use python3.6 environment, this problem also exists)
> * MacOS BigSur 11.1
> 
> ### Priority
> I tried so many ways to solve it. But cannot solve it at all.
> 
> Please help me

Problem Soveld! 

replace "vispy/ext/cocoapy.py" 

```
923 cf = cdll.LoadLibrary(util.find_library('CoreFoundation'))
```
to
```
cf = cdll.LoadLibrary('/System/Library/Frameworks/CoreFoundation.framework/Versions/Current/CoreFoundation')
```

Thanks! https://github.com/vispy/vispy/issues/1885#issuecomment-749157311

**Comment by djhoese** [comment] 2021-01-08 17:58
Duplicate of #1885. Thanks.

**Closed by djhoese** 2021-01-08 17:58 UTC
