### ISSUE TITLE
plot mesh rotation messing up faces

### ISSUE THREAD

**Issue by bendichter** [vispy/vispy#1151] opened 2016-01-13 01:38 UTC
Hi,

I am plotting a mesh that is a cortex using the following script:
 ```
fig = Fig()
ax = fig[0, 0]
m = ax.mesh(vertices=vert, faces=tri, color=[.5, .5, .5])
app.run()
```

what I get initially looks pretty good:
![screen shot 2016-01-12 at 5 16 21 pm](https://cloud.githubusercontent.com/assets/844306/12282142/a9152512-b950-11e5-8c7d-a3d107ad91a5.png)

however, when I rotate the mesh by dragging my mouse, the faces get messed up:
![screen shot 2016-01-12 at 5 16 29 pm](https://cloud.githubusercontent.com/assets/844306/12282147/bf2fe8dc-b950-11e5-936e-25388ed1d9c3.png)

Rotating back gives the original good faces.

Here's something I observed that may be a hint: You can change which orientation looks good by changing the order in which the tri's are listed e.g. tri = np.column_stack((tri[:,2],tri[:,1],tri[:,0])).

By the way, I found that mesh does not like vertices in float64, and threw an error, so in order to get this to work I had to recast my vertices in float32. It would be nice if this happened automatically, or was indicated in the documentation for mesh.

I know the data is good because I can get it to look right in MATLAB, but I would love to get this working in vispy, and really appreciate any help any of you could give!

Ben

**Comment by almarklein** [comment] 2016-03-11 13:21
Looks like a duplicate of #896

**Closed** 2016-03-11 13:21 UTC

**Comment by bendichter** [comment] 2016-03-12 05:52
yup, `fig = Fig(config={'depth_size': 24})` fixed it. Thanks!
