### ISSUE TITLE
Canvas not repsonsive on IPython 5.1

### ISSUE THREAD

**Issue by gbaruch** [vispy/vispy#1293] opened 2016-11-06 12:19 UTC
Hi,
I'm using vispy to render some 3d mesh data. I'm using anaconda. 
It worked well when running through regular python, but when running from a jupyter notebook the canvas became not responsive.
Trying to resolve this, I found out that on an old env I got it was working, so I tried finding the difference, Finally I found out that when I forced ipython to downgrade to "ipython=4.1.2=py27_1" instead of "ipython=5.1.0=py27_0" it worked.
Hope it will help you somehow.

**Comment by orodbhen** [comment] 2017-04-04 11:48
I can confirm that VisPy doesn't work at all in IPython 5. The window doesn't open until I press `CTRL+D` and then it has to be force closed.

Reverting to IPython 4.2 gets it working, but the interaction with the plot is slow and choppy. It's as if there was no GPU acceleration. This occurs for both the integrated and discrete GPUs. Running the app outside IPython works as expected, with smooth interaction. 

Mint 18.1 Cinnamon x86_64
Anaconda Python 2.7
GPU: Intel Corporation Device 191d
DGPU: NVIDIA Quadro M1000M

**Comment by liubenyuan** [comment] 2017-10-16 08:55
I can confirm that, vispy under windows can only work with native python interpreter (for example, pycharm). Vispy window keep saying not responding under windows when runs from spyder (with ipython backend)

**Comment by davidh-ssec** [comment] 2017-10-16 13:47
@liubenyuan Are you using vispy from github master or from PyPI (pip install)?

**Comment by liubenyuan** [comment] 2017-10-16 14:37
@davidh-ssec I am using vispy from github and install from source code.

**Comment by davidh-ssec** [comment] 2017-10-31 00:48
Do any of you have a test case/code of what you are trying to run?

**Comment by davidh-ssec** [comment] 2017-10-31 01:03
If you do `%gui qt` and `%pylab qt` before importing your modules you should be able to get things working. You could also modify `~/.ipython/profile_default/ipython_config.py` and make these settings permanent:

```
c.TerminalIPythonApp.gui = 'qt'
c.TerminalIPythonApp.pylab = 'qt'
```

Please let me know if this helps.

**Comment by liubenyuan** [comment] 2017-10-31 11:12
hi, `%pylab qt` changes the default backend of ipython from `inline` to `qt`, which solves the problem. 

However, put 
```
c.TerminalIPythonApp.gui = 'qt'
c.TerminalIPythonApp.pylab = 'qt'
```
in ipython config files seems not working. I am using spyder 3 under windows 10, 64 bit.

**Comment by davidh-ssec** [comment] 2017-10-31 14:29
@liubenyuan I'm guessing that spyder uses its own configs for its ipython terminal or imports the necessary bits so the default ipython configs probably won't work. I'll see if I can find information on this.

**Comment by liubenyuan** [comment] 2017-11-01 00:05
Yes. I think switching to `qt` backend can solve my problem now and i can continue debug my vispy programs.

**Comment by davidh-ssec** [comment] 2017-11-01 01:55
@liubenyuan You may be able to find the proper configs in `~/.jupyter`. It seems not every jupyter console has configs by default but you can generate it (`--generate-config`). For example, for notebook http://jupyter-notebook.readthedocs.io/en/stable/config.html. I'm not sure if this makes sense outside of ipython since that's where that gui and pylab config value is, but anyway I thought I'd write this down somewhere.

As far as I know there is no way to "inline" a OpenGL canvas inside ipython. I'm not sure if that's what you expected. Looks like @campagnola and other pyqtgraph folks got some cool stuff working for them: https://groups.google.com/forum/#!topic/pyqtgraph/Nu921kIkeFk
But this seems to be a hack more than a feature since any animation would require regenerating an image every frame. Or at least that's how I understand it.

I'm closing this for now since it seems to be working well enough. I'll have to add information about these ipython commands in the documentation somewhere.

**Closed by davidh-ssec** 2017-11-01 01:55 UTC
