### ISSUE TITLE
ArrowVisual heads not displayed correctly in top view perspective

### ISSUE THREAD

**Issue by shredEngineer** [vispy/vispy#1940] opened 2020-10-17 15:48 UTC
When drawing arrows using `ArrowVisual`, the arrow heads deform into a square when rotating the perspective into the top view plane. The error occurs regardless of the `arrow_type`, and also regardless if the arrow points down or up into the plane.

This is the relevant code I use to display the arrows (inside a `scene.SceneCanvas` and using a `TurntableCamera`):
```
v = scene.visuals.create_visual_node(visuals.ArrowVisual)(
    parent=self.view.scene,
    arrow_type="triangle_60",
    connect="segments"
)

v.set_data(pos=pos, arrows=arrows, color=np.repeat(colors, 2, axis=0))
v.arrow_size = 4
v.arrow_color = colors
```

Here is a very short video demonstrating the issue: [Go to Video (imgur)](https://imgur.com/a/7sTLD4Y)

How can this behaviour be prevented? Am I missing something?

**Comment by djhoese** [comment] 2020-10-17 17:26
Duplicate of #1917

**Closed by djhoese** 2020-10-17 17:26 UTC
