### ISSUE TITLE
ViewBox does not receive mouse double click events from canvas

### ISSUE THREAD

**Issue by aliounis** [vispy/vispy#1801] opened 2019-12-31 15:22 UTC
It appears that as currently implemented double press events die at the canvas and must be manually passed to the viewboxes in the canvas by doing

```
canvas = MyCanvas(keys='interactive')
vb = ViewBox(parent=canvas.scene)
# add a double click emmitter to the viewbox
vb.events.add(mouse_double_click=Event)
# connect the _process_mouse_event method to the mouse_double_click emitter in canvas
canvas.events.mouse_double_click.connect(canvas._process_mouse_event)
```

where MyCanvas subclasses Canvas and overrides _process_mouse_event to change the line
```deliver_types = ['mouse_press', 'mouse_wheel']``` 
to
```deliver_types = ['mouse_press', 'mouse_wheel', 'mouse_double_click']```

Is this an intentional design decision? If not the above fix would be easy to implement in the source (adding a mouse_double_click event to the viewboxes by default and connecting the modified _process_mouse_event to the canvas mouse_double_click emitter)

**Comment by djhoese** [comment] 2020-01-02 15:28
I *think* this is by design. First, is your `MyCanvas` subclassed from the `SceneCanvas` or the `Canvas` class? Based on the rest of your code I would expect `SceneCanvas`, but I wanted to make sure.

As you may have seen by looking through the code the `_process_mouse_event` method on the `SceneCanvas` is added as an event handler for the various mouse events here:

https://github.com/vispy/vispy/blob/ec73d04e82849971c68436c46d769f15874a20af/vispy/scene/canvas.py#L138-L141

This handler is a convenience function for the picking (what visual was clicked on) and camera functionality provided by the SceneCanvas. So I think the `deliver_types` are specifically meant to know what events should be passed to parent Visuals. This means that if you click on a "box" visual on the Canvas that the SceneCanvas will try handling the mouse event with that visual. If the box doesn't handle it, then move on to the next parent node, eventually ending on the ViewBox where a Camera may exist and should handle the mouse event. So I think the `_process_mouse_event` method is only saying that it won't propagate the double click, not necessary that it isn't handling it at all (it is likely giving it to the Visual being clicked on).

So based on what I'm reading I think the double click is not handled here because:

1. Not all backends support native double click events and vispy tries its best to simulate this for those backends. The SceneCanvas mouse handling may be reflecting this (depending on when it was originally added to vispy and the double click issues were known).
2. Double click events aren't currently used by the available cameras. If you are making your own camera and *want* the double click event then I could see your suggested change being needed.
3. You shouldn't need to use the events sent from the `_process_mouse_event` method, but rather connect `canvas.events.mouse_double_click` directly to whatever viewbox (or other object) method you want to handle the event.

So I guess the question is, what do you want to do with the double click event? Maybe we can figure out the best solution based on your particular task. I'm not against adding the double click to the deliver types, but I'm not quite sure it is needed yet either.

Thanks for posting this. Good question.

**Comment by aliounis** [comment] 2020-01-03 15:01
First, yes MyCanvas is subclassing SceneCanvas. Sorry about the confusion on that.

Now as for what I am doing: I am embedding vispy into a larger qt application for viewing/manipulating data overlaid on 3D topography which has 2 viewboxes (one in 3d and one constrained to a 2d overhead with a custom camera).  The viewboxes are added to the scene using `canvas.central_widget.add_grid()`. 

The data being viewed is usually encoded using a colormap, but occasionally it is desirable to be able to see the raw data directly in table format. To enable getting to this table I implemented a QTable widget in a QDialog box that pops up when the user double clicks on a grid cell in either of the 2 viewboxes.  I implemented this using the steps discussed in my original post.  The problem I was experiencing was that the double click events were not passed to the viewboxes by default which I found confusing because other mouse events were.  In fact, from what I can tell, they weren't being passed anywhere (but perhaps I just didn't dig enough).  As you said, I could just connect to the canvas double click event emitter, but for my application I needed to know which viewbox the event occurred in so that I could properly transform the event coordinates into data space coordinates and determine which data to display.  This would have required using the visual_at method of the SceneCanvas to determine which viewbox the click occurred in (I think) so I just connected the `_process_mouse_event` to the emitter instead since it did this anyway, then I could just connect a handler to the double click emitter for each viewbox.  Maybe I could have just used event.source to get this same information, but I'm not sure if that's set at the `SceneCanvas` level or if it is set by the event managers on the viewboxes themselves.

**Comment by djhoese** [comment] 2020-01-06 18:29
Sorry for the slow reply. I came down with a cold on Friday and it hit me hard.

Regarding `.source`, I think that is always the current Canvas object, right?

Based on what you want to do I don't think what you did is wrong. It sounds like you've realized the two options already:

1. Subclass the SceneCanvas and override the `_process_mouse_event` so it passes the double click event on.
2. Use the Canvas's double click event directly by connecting it to your own method that does the picking logic (essentially reimplementing what the Canvas does).

I can see pros and cons to both approaches. I'm not sure I agree with adding the double click to the `deliver_types` in vispy since it is not being used and this method is meant to be specific to the SceneCanvas and for what it is doing. I'm open to discussion though.

**Comment by aliounis** [comment] 2020-01-07 14:12
I've found that at the canvas event level, ``.source`` is the current scenecanvas object, but when the event is propagated through ``_process_mouse_event`` then event.souce changes to be the viewbox that the event gets passed through (which helps to simplify my code).

I'm fine with not making this a default part of the code but it might be good to include an example or a discussion in the documents, because it wasn't intuitive to me (without digging through the source code and doing some debugging) why the viewboxes weren't receiving the double click events when they were receiving other mouse events.  I could probably try to make an example or documentation blurb sometime this week if you think this would be a good idea.

Thanks for working on this project.  I've been waiting a long time for a capable opengl based renderer for python since mplot3d has numerous performance issues and I'm hoping in time vispy can fill that void.

**Comment by djhoese** [comment] 2020-01-07 14:17
Sounds good. It would be great if you could make a blurb that could be added to the `_process_mouse_event` docstring. You could either post it here or even make a pull request with the change if that's something you are comfortable with.

**Comment by queenish001** [comment] 2021-11-06 03:44
@aliounis Is your doubt resolved now?

**Comment by djhoese** [comment] 2021-11-06 19:18
Going to close this. @aliounis if you have ideas for how the docstring could be improved my previous comment still stands.

**Closed by djhoese** 2021-11-06 19:18 UTC
Labels: type: question
