### ISSUE TITLE
compatible with Big Sur python3.8

### ISSUE THREAD

**Issue by Zhenghao-Dai** [vispy/vispy#1977] opened 2021-01-21 13:10 UTC
```
Traceback (most recent call last):
  File "cmdVelocityCircle.py", line 29, in <module>
    swarm = Crazyswarm()
  File "/Users/zhenghaodai/my_copy_crazy/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm.py", line 40, in __init__
    self.timeHelper = TimeHelper(args.vis, args.dt, args.writecsv, args.disturbance)
  File "/Users/zhenghaodai/my_copy_crazy/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflieSim.py", line 19, in __init__
    from .visualizer import visVispy
  File "/Users/zhenghaodai/my_copy_crazy/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/visualizer/visVispy.py", line 5, in <module>
    from vispy import scene, app, io, geometry
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/site-packages/vispy/ext/cocoapy.py", line 930, in <module>
    cf.CFStringCreateWithCString.restype = c_void_p
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/opt/anaconda3/envs/crazyswarm/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found
```
I'm using python3.8 and I have updated anacoda3 to the latest version. Is this a compatible problem. What should I do to solve this problem? It works fine before

**Comment by djhoese** [comment] 2021-01-21 15:56
Duplicate of #1885

**Closed by djhoese** 2021-01-21 15:56 UTC
