### ISSUE TITLE
lintian  warning and error during the build process of the 0.4.0 version

### ISSUE THREAD

**Issue by picca** [vispy/vispy#1066] opened 2015-08-18 16:03 UTC
Hello, I just put here the errormessage thaht I got from our quality tool, In order to discuss about this. Mosly proble with some javascript embeded or minified.

N: Using profile debian/main.
N: Setting up lab in /tmp/temp-lintian-lab-4OsX6AoEWQ ...
N: Unpacking packages in group vispy/0.4.0-1
N: ----
N: Processing changes file vispy (version 0.4.0-1, arch source all) ...
N: ----
N: Processing source package vispy (version 0.4.0-1, arch source) ...
E: vispy source: source-is-missing vispy/html/static/js/jquery.mousewheel.min.js
N: 
N:    The source of the following file is missing. Lintian checked a few
N:    possible paths to find the source, and do not find it.
N:    
N:    Please repack your package to include the source or add it to
N:    "debian/missing-sources" directory.
N:    
N:    If this is a false-positive, please report a bug against Lintian.
N:    
N:    Severity: serious, Certainty: possible
N:    
N:    Check: cruft, Type: source
N: 
E: vispy source: source-is-missing vispy/html/static/js/vispy.min.js

W: python-vispy: embedded-javascript-library usr/lib/python2.7/dist-packages/vispy/html/static/js/jquery.mousewheel.min.js please use libjs-jquery-mousewheel
N: 
N:    This package contains an embedded copy of JavaScript libraries that are
N:    now available in their own packages (for example, JQuery, Prototype,
N:    Mochikit or "Cropper"). Please depend on the appropriate package and
N:    symlink the library into the appropriate location.
N:    
N:    Refer to Debian Policy Manual section 4.13 (Convenience copies of code)
N:    for details.
N:    
N:    Severity: normal, Certainty: possible
N:    
N:    Check: files, Type: binary, udeb
N: 
N: ----
N: Processing binary package python3-vispy (version 0.4.0-1, arch all) ...
W: python3-vispy: debian-changelog-has-wrong-weekday 2015-08-18 is a Tuesday
E: python3-vispy: copyright-should-refer-to-common-license-file-for-gpl
I: python3-vispy: using-first-person-in-description line 13: We
W: python3-vispy: embedded-javascript-library usr/lib/python3/dist-packages/vispy/html/static/js/jquery.mousewheel.min.js please use libjs-jquery-mousewheel
N: ----
N: Processing binary package python-vispy-doc (version 0.4.0-1, arch all) ...
W: python-vispy-doc: debian-changelog-has-wrong-weekday 2015-08-18 is a Tuesday
E: python-vispy-doc: copyright-should-refer-to-common-license-file-for-gpl
I: python-vispy-doc: using-first-person-in-description line 13: We
E: Lintian run failed (policy violation)

**Comment by Eric89GXL** [comment] 2015-08-18 16:05
@picca is there some minimal script we can use to reproduce this check locally? In other words, given we have `vispy` checked out or built in some directory, can we easily check the Debian compatibility? It would be nice if we could, because then we could have `Travis` run these checks on every build. I work on a couple repos that could potentially benefit from such a thing.

**Comment by picca** [comment] 2015-08-18 16:14
In fact in orderto run lintian, you need to build the package the debian way and then run lintian on it.
If I remember correctly travis can install debian/ubuntu packages.
so maybe it could be possible to run the command needed to generate de debianpackage and lintian.

**Comment by Eric89GXL** [comment] 2015-08-18 16:16
Yeah, it should be possible. Do you have some shell script you're currently using to do it, or are you doing it on the fly? If you can put the commands into a script, I can probably get Travis to do it.

**Comment by Eric89GXL** [comment] 2015-08-18 16:19
Also related to packaging: bits of #1065

**Comment by picca** [comment] 2015-08-18 16:26
we need to put the debian directory in the repository and then install the debhelper, lintian
run
dpkg-buildpackage
lintian

and I think that it's all,maybe there is some exemple of debian package building with travis

**Comment by picca** [comment] 2015-08-18 16:43
Is it possible to put all the bundled javascript also into _bundle and to provide a way to set a variable with the path of the library.

here an example of what is done in spyder.
I just maintain this patch in the packaging.

--- a/spyderlib/__init__.py
+++ b/spyderlib/__init__.py
@@ -35,6 +35,10 @@ __forum_url__   = 'http://groups.google.com/group/spyderlib'
 # Dear (Debian, RPM, ...) package makers, please feel free to customize the
 # following path to module's data (images) and translations:
 DATAPATH = LOCALEPATH = DOCPATH = MATHJAXPATH = JQUERYPATH = ''
+DATAPATH = '/usr/share/spyderlib/images'
+DOCPATH = '/usr/share/doc/python-spyderlib-doc/html'
+MATHJAXPATH = '/usr/share/javascript/mathjax'
+JQUERYPATH = '/usr/share/javascript/jquery'

**Comment by Eric89GXL** [comment] 2016-05-19 20:13
Closing since we're trying to put out 0.5 now

**Closed by Eric89GXL** 2016-05-19 20:13 UTC
