### ISSUE TITLE
magnify.py example doesn't work well on intel i3-350m with switchable graphics (to amd hd5650), when on intel

### ISSUE THREAD

**Issue by stonebig** [vispy/vispy#923] opened 2015-05-24 08:38 UTC
hi,

When on HD5650, I have the nice loop effect on 4 different Viewboxes.

When on intel graphics, I have roughly only the Top Viewbox visible, and it seems to display "Z" lines instead of a magnification.
![magnifying_issue_on_intel_inside_i3_350](https://cloud.githubusercontent.com/assets/4312421/7787229/0a9f0062-0201-11e5-995c-b8c3715e08ef.png)

**Comment by Eric89GXL** [comment] 2015-05-24 20:00
whoaa, that's a weird one :) Is this the graphics card with GL 2.1 capabilities only? I wonder if this is some other limitation of 2.1 that we're hitting without detecting it.

**Comment by stonebig** [comment] 2015-05-24 20:19
detail of errors in the IDLE console:
````
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
WARNING: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\idlelib\run.py", line 126, in main
    ret = method(*args, **kwargs)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\idlelib\run.py", line 353, in runcode
    exec(code, self.locals)
  File "D:\result_tests\winpython-3.4.3.3\notebooks\magnify.py", line 97, in <module>
    vispy.app.run()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\app\_default_app.py", line 61, in run
    return default_app.run()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\app\application.py", line 123, in run
    return self._backend._vispy_run()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\app\backends\_qt.py", line 217, in _vispy_run
    return app.exec_()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\app\backends\_qt.py", line 631, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\util\event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\util\event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\gl\_gl2.py", line 53, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\gl\gl2.py", line 59, in _get_gl_func
    func = getattr(_lib, name)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\ctypes\__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\ctypes\__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'glBindFramebuffer' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\util\event.py", line 448, in _invoke_callback
    cb(event)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\canvas.py", line 189, in on_draw
    self._draw_scene()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\canvas.py", line 232, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\canvas.py", line 282, in draw_visual
    visual.draw(scene_event)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 23, in process
    node.draw(event)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\widgets\viewbox.py", line 324, in draw
    self.scene.draw(event)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\scene\systems.py", line 23, in process
    node.draw(event)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\visuals\line\line.py", line 275, in draw
    self._line_visual.draw(transforms)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\visuals\line\line.py", line 389, in draw
    self._program.draw('line_strip')
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\visuals\shaders\program.py", line 89, in draw
    Program.draw(self, *args, **kwargs)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\program.py", line 467, in draw
    canvas.context.flush_commands()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\context.py", line 163, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\glir.py", line 401, in parse
    self._parse(command)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\glir.py", line 329, in _parse
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, 0)
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\gl\_gl2.py", line 55, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native = _get_gl_func("glBindFramebuffer", None, (ctypes.c_uint, ctypes.c_uint,))
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\lib\site-packages\vispy\gloo\gl\gl2.py", line 77, in _get_gl_func
    raise RuntimeError('Function %s not present in context.' % name)
RuntimeError: Function glBindFramebuffer not present in context.
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 2
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 3
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 4
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 5
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 6
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 7
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 8
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 9
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 10
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x265df10>> repeat 20
>>> 
````

**Comment by Eric89GXL** [comment] 2015-05-25 01:09
Thanks for the report. This looks like the same OpenGL 2.1 error that was mentioned in #921. This would make it a duplicate of #669. (FYI mentioning #669 in this issue will make us see this issue when looking at #669.) I'm going to close this, but feel free to reopen if you think the problem is different.

**Closed by Eric89GXL** 2015-05-25 01:09 UTC
