### ISSUE TITLE
AssertionError when trying to transform a scene.visuals.Cube with a visuals.transforms.MatrixTransform

### ISSUE THREAD

**Issue by skidzo** [vispy/vispy#1082] opened 2015-09-07 16:30 UTC
AssertionError, here the minimal example (at he end of the post...):

Traceback (most recent call last):
  File "/home/johannes/VisualsTransformsMatrixTransform.py", line 37, in <module>
    cube.trafo(x=-0.5,y=1.5)
  File "/home/johannes/VisualsTransformsMatrixTransform.py", line 26, in trafo
    self.transform = self.transform.translate([x,y,z])
  File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/frozen.py", line 17, in **setattr**
    object.**setattr**(self, key, value)
  File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/node.py", line 366, in transform
    assert isinstance(tr, BaseTransform)
AssertionError

and also, when you click left and right mousebutton at once:

> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(**kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> repeat 2
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(__arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent
> > > WARNING: Traceback (most recent call last):
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 378, in mouseMoveEvent
> > >     modifiers=self._modifiers(ev),
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/base.py", line 202, in _vispy_mouse_move
> > >     ev = self._vispy_canvas.events.mouse_move(_*kwargs)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 346, in _process_mouse_event
> > >     getattr(picked.events, event.type)(scene_event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
> > >     self._invoke_callback(cb, event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
> > >     self, cb_event=(cb, event))
> > >   << caught exception here: >>
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
> > >     cb(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/perspective.py", line 224, in viewbox_mouse_event
> > >     self._update_rotation(event)
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 60, in _update_rotation
> > >     Quaternion(*_arcball(self._event_value, wh)) *
> > >   File "/home/johannes/anaconda3/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/cameras/arcball.py", line 99, in _arcball
> > >     x, y = -(2. \* x - w) / r, (2. \* y - h) / r
> > > TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
> > > ERROR: Invoking <bound method ArcballCamera.viewbox_mouse_event of <ArcballCamera at 0x7fad3cd3a4a8>> for SceneMouseEvent

 (i am using a pen so this is actually happening everytime i touch the screen...)

"""
Created on Mon Sep  7 18:15:47 2015

@author: johannes
"""

import os,sys
import numpy as np
from vispy import app,gloo,scene,visuals
from vispy.scene.visuals import create_visual_node
from vispy.visuals.transforms import STTransform,MatrixTransform

class dummy(scene.visuals.Cube):
    """
    creates a custom draft to demonstrate what is not working
    """
    def **init**(self,view,x,y,z,face_color,edge_color):
        scene.visuals.Cube.**init**(self,(x,y,z),color=face_color,edge_color=edge_color,parent=view)

```
def trafo(self,x=0.,y=0.,z=0.,angle=0.,al=0.,be=0.,ga=0.):
    #Not Working
    self.transform = MatrixTransform()

    self.transform = self.transform.translate([x,y,z])
    self.transform = self.transform.rotate(angle,[al,be,ga])
```

canvas = scene.SceneCanvas(keys='interactive', bgcolor='white',
                           size=(800, 600), show=True)

view = canvas.central_widget.add_view()
view.camera = 'arcball'

cube = dummy(view.scene,2,3,1,'red','black')
cube.trafo(x=-0.5,y=1.5)

view.camera.set_range(x=[-3, 3])

if **name** == '**main**' and sys.flags.interactive == 0:

```
canvas.app.run()
```

**Comment by queenish001** [comment] 2021-11-20 06:48
@djhoese

**Comment by djhoese** [comment] 2021-11-20 23:51
The problem is that `MatrixTransform.translate` and `.rotate` are inplace operations and don't return anything (return None). If you remove the `self.transform = ` part of those calls then it should work...or at least work differently. Given the age of this issue I'm going to close this. Feel free to comment and we can reopen.

**Closed by djhoese** 2021-11-20 23:51 UTC
