### ISSUE TITLE
Multi-Window support for scene module

### ISSUE THREAD

**Issue by dzusan** [vispy/vispy#1603] opened 2019-03-19 14:06 UTC
I try to create multiple windows to display different datasets through `scene` module.
```
class Canvas(scene.SceneCanvas):
    def __init__(self, wq=None, *args, **kwargs):
        scene.SceneCanvas.__init__(self, *args, **kwargs)

        self.unfreeze() # to allow addition of new attributes
        self.wq = wq

        self.view = self.central_widget.add_view()
        self.view.camera = scene.PanZoomCamera(rect=(-100, -10, 200, 300),
                                               aspect=1.0)

        self.show()

        self.markers = scene.Markers(parent=self.view.scene)
        self.timer = app.Timer('auto', connect=self.on_timer, start=True)

        self.freeze()

    def on_timer(self, event):
        repkgAreas = self.wq.get()
        self.markers.set_data(pos=repkgAreas['Position'],
                              face_color=repkgAreas['Color'],
                              size=repkgAreas['Size'],
                              symbol='square')
        self.context.clear()
        self.markers.draw()
        self.update()

if __name__ == "__main__":
    from queue import Queue
    q1 = Queue()
    cmap = cm.rainbow
    norm = colors.Normalize(vmin=-20, vmax=30)

    for i in range(1000):
        testData = {}

        testData['Position'] = np.random.rand(100, 2) * 25
        testData['Size'] = np.full(100, 17)

        colorInit = np.full(100, 17)
        testData['Color'] = np.array(cmap(norm(colorInit)))
        alpha = np.full(100, 0.5)
        testData['Color'][:,3] = alpha

        testData['Num'] = i

        q1.put(testData)

    Canvas(wq=q1)
    Canvas(wq=q1)
    app.run()
```
Both windows are opening simultaneously, but only first displays data (with huge freezes), second remain black. The console spamming following messages:
```
WARNING: Error drawing visual <Markers at 0x22988522780>
WARNING: Error drawing visual <Markers at 0x2298caf84e0>
```
Through `app.Canvas` class I can create two windows and enjoy stable work, but I need `scene` features like zoom and other.

Setup:
* Windows 10 
* Python 3.6.6
* vispy 0.5.3 (from pip install)
* PyQt4 or PyQt5 (nevermind, i tried both)

**Comment by djhoese** [comment] 2019-03-19 15:01
Why do you have the `self.context.clear()` in the timer method? What happens if you remove that and the explicit `self.markers.draw()`?

**Comment by dzusan** [comment] 2019-03-19 18:31
Bingo! If I leave only self.update(), the problem is partially solved. I have assembled my code from several examples and don't remember why I pasted this.
But, I still can't use this. First window play in proper time, but the others play slower than first and delay is growing in time. Console is silent unfortunately.

**Comment by djhoese** [comment] 2019-03-19 18:36
Great. One step at a time I guess. Next, what happens if you use the current github master branch (what will become the 0.6 release)? I could be misremembering things but I think there was a recent memory leak fixed in the MarkersVisual. If you monitor memory usage with this, what does it look like? Given how you are creating the Queue (filling it completely before using it), what happens if you fill the Queue, sleep for 5 seconds, then continue on with processing. What does the memory usage look like?

**Comment by dzusan** [comment] 2019-03-20 21:17
Yesterday I run app at home and reported this issue. Today I run exactly the same code in my office and it worked as it should! I updated vispy to github v0.6 and it worked the same. Now I try again at home and see old problem. Updating vispy to v0.6 does not affect. Memory usage is fine in any configuration. Im really confused. This is differences list between home and office machine that could play in my opinion:
* office / home
* windows 7 / windows 10
* integrated intel video / integrated intel video + discrete card

**Comment by kmuehlbauer** [comment] 2019-03-20 21:22
@dzusan We had issues reported with integrated Intel graphic adapters. Good chance that this might fit here.

**Comment by dzusan** [comment] 2019-03-21 07:48
@kmuehlbauer If the problem is really in the graphic adapter, it's geforce gtx1050ti on the home machine. Because with integrated intel on the office machine app works great. Can I configure vispy to use exactly integrated intel graphics?

**Comment by djhoese** [comment] 2019-03-21 12:28
@dzusan Using one GPU over the other is usually an operating system setting (from my understanding) and isn't available with all GPUs/OSes.

**Comment by kmuehlbauer** [comment] 2019-03-21 12:53
@dzusan Yes, now i'm seeing it too. :disappointed:

**Comment by dzusan** [comment] 2019-03-23 12:47
During using my app this out of sync between windows rise randomly. And finally I found the problem. It was blocking queue reading in update method. And as far as all windows run in the same thread, while one is trying to read queue, the other is frozen.

Firstly I tried to spread windows to threads by standard python threading module, but failed:
```
WARNING: QObject::startTimer: QTimer can only be used with threads started with QThread
```
Second I tried to use QThread:
```
class SimpleThread(QThread):
    def __init__(self, q, parent=None):
        QThread.__init__(self, parent)      
        Canvas(wq=q)

def ObjRender(*args):
    threads = []
    for q in args:
        threads.append(SimpleThread(q))
        threads[-1].start()
    app.run()
```
But, the windows were closing after I run app with:
```
WARNING: QApplication::exec: Must be called from the main thread
```
Then I found simple solution such as non-blocking queue reading (and at the time I think it looks like a hack):
```
def on_timer(self, event):
    frame = self.wq.get_nowait()
    if frame:
        pkgFrame = repacking(frame)
        self.markers.set_data(pos=pkgFrame['Position'])
        self.update()
```
It works properly, but console spams:
```
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x1a46690a978>> repeat 8192
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x1a45ae89128>> repeat 8192
```
Do you think this is the right way? And how to mute the endless messages?

**Comment by djhoese** [comment] 2019-03-23 14:12
You've found some of this yourself, but here are some things I would suggest:

1. Don't mix regular python threads and QThreads.
2. I think I mentioned this on gitter: don't put "drawing" operations on background threads. All GUI/drawing operations must be done on the main thread.
3. Doing something in a QThread's `__init__` does not perform this operation on a separate thread. Those operations must be done via signals and slots. The hacky way of doing some things like this is to override `def run` in your QThread subclass, but last I checked this is not the preferred solution of doing things.
4. Having anything on the main thread that "waits" or does a for loop on events is not going to work. The Qt event loop operates on single short events. The event loop of the main thread handles an event, then moves on to the next one.
5. I'm not sure how you implemented everything but your idea of using a timer that then triggers `on_timer` with one single operation seems like a good solution.

**Comment by dzusan** [comment] 2019-03-24 15:59
Thank you for advices. It's working fine as is, so far. Now I have a good experience with vispy.

**Comment by djhoese** [comment] 2019-03-24 21:50
I'm going to close this for now. If you have more issues feel free to reopen this or create a new issue if the issue is different enough.

**Closed by djhoese** 2019-03-24 21:50 UTC
