### ISSUE TITLE
bug in the console when closing the window with PyQt4

### ISSUE THREAD

**Issue by jvtrudel** [vispy/vispy#846] opened 2015-03-30 21:04 UTC
I got an error when I close the window using esc command while running example/tutorial/app/interactive.py . Maybe it is not the way it should be closed, but it should close silently anyway. no?

```
....
raise RuntimeError('Gloo requires a Canvas to run.\n' + msg)
RuntimeError: Gloo requires a Canvas to run.
If you want to use gloo without vispy.app, use a gloo.context.FakeCanvas.
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> for Event
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> repeat 2
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> repeat 3
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> repeat 4
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> repeat 5
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> repeat 6
ERROR: Invoking <bound method Canvas.on_timer of <Canvas (PyQt4) at 0x110c42750>> repeat 7
...
...
...
...
```

**Comment by Eric89GXL** [comment] 2015-03-30 22:50
Looks like the closing of the last canvas is not automatically killing the timer. I assumed it should... thanks for the report.

**Comment by djhoese** [comment] 2020-08-31 20:26
I'm unable to reproduce this with PyQt5 with the current master branch. If someone runs into this again please file a new issue.

**Closed by djhoese** 2020-08-31 20:26 UTC
Labels: type: bug
