### ISSUE TITLE
Transform system mapping with fly camera

### ISSUE THREAD

**Issue by os-gabe** [vispy/vispy#1699] opened 2019-08-27 00:19 UTC
I noticed that when using the fly camera ` self.view.camera.transform.map(pos)` does not map scene coordinates to screen coordinates how it does with the other cameras (panzoom, arcball, turntable).

Any help with figuring out whats going on here would be appreciated.

**Comment by freckletonj** [comment] 2020-03-22 22:08
Here's a PR I found for point picking that uses transforms similarly, I still haven't gotten it to work with the FlyCamera. If I plot the data after the transform, it's clearly _related_ to the `Markers` I've plotted, but they're not aligned at all.

https://github.com/vispy/vispy/blob/64e76c40c8d7d38efc53c9a1a50ca7f336b9ffc2/examples/basics/scene/points_selection.py#L145

**Comment by freckletonj** [comment] 2020-03-22 22:24
Actually, for my use case this solved it: https://github.com/vispy/vispy/issues/1198#issuecomment-212790199

so:

```python

self.tr = self.markers.transforms.get_transform(map_from='visual', map_to='canvas')
data = self.tr.map(self.data)
data /= data[:, 3:]
data = data[:, :2]


```

**Comment by djhoese** [comment] 2020-03-23 14:05
@freckletonj As far as I understand, the solution you are talking about was already implemented in the last release of VisPy from this PR: https://github.com/vispy/vispy/pull/1743

What version of VisPy are you using?

**Comment by freckletonj** [comment] 2020-03-23 15:02
@djhoese I'm using `0.6.2`, and it looks like the PR you mention merged in `0.6.3`, so I am indeed not using those commits.

But for my understanding, I don't see where this is "fixed" in that PR, and from the comment I linked above (https://github.com/vispy/vispy/issues/1198#issuecomment-212790199), it sounds like the behavior I worked around was expected, and not a bug, no?

**Comment by djhoese** [comment] 2020-03-23 15:24
Ah you're right. I remembered discussing this and that comment in the issue but re-reading the comments it looks like the normalization wasn't needed for #1743. Regardless, glad you got it working.

**Comment by queenish001** [comment] 2021-11-03 22:07
@djhoese This issue can be closed.

**Closed** 2021-11-04 01:51 UTC
Labels: type: question
