### ISSUE TITLE
memory leak in vispy

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#827] opened 2015-03-27 21:28 UTC
Below is a minimal example. When pressing the r key a random is image is loaded as an ImageVisual.
The memory leak is still present after recent fixes #784, #790.

    from __future__ import division
    
    #%% Load packages
    import os,sys
    import numpy as np
    import vispy.app
    from vispy import gloo
    from vispy import visuals
    from vispy.visuals.transforms import STTransform, TransformSystem
    from PySide import QtGui, QtCore
    
    class DosWindow(QtGui.QMainWindow):
        verbose=1
        def __init__(self, image):
            super(DosWindow, self).__init__()
            self.setGeometry(0, 0, 800, 600 )
            self.canvas = Canvas(image)
            self.image = image.copy()
            layout = QtGui.QVBoxLayout()
            layout.addWidget(self.canvas.native)
            layout.setContentsMargins(QtCore.QMargins(0, 0, 0, 0))
            central_widget = QtGui.QWidget()
            central_widget.setLayout(layout)
            self.setCentralWidget(central_widget)
            self.show()
    
        def keyPressEvent(self, event):
            if event.key() == QtCore.Qt.Key_Q:
                exit(0)
            if event.key() == QtCore.Qt.Key_R:
                newimage=(0.4*np.random.rand()) + self.image            
                self.canvas.setImage( newimage )
                self.canvas.update()
                print('reload image')
    
    class Canvas(vispy.app.Canvas):
        def __init__(self, image):
            super(Canvas, self).__init__()
    
            self.size = ((image.shape[1]) , image.shape[0] )
            self.imsize=self.size
            self.setImage(image)
    
            # Create a TransformSystem that will tell the visual how to draw
            tr_sys = TransformSystem(self)
            tr_sys.visual_to_document = self.image_transform
            self.transform_system=tr_sys
    
        def setImage(self, image):
            self.image = visuals.ImageVisual(image, method='subdivide')
            self.image_transform=STTransform(scale=(1, 1), translate=(0, 0))
    
        def on_draw(self, ev):
            gloo.clear(color='white', depth=True)
            gloo.set_viewport(0, 0, *self.size)
            self.image.draw(self.transform_system)
    
    if __name__ == '__main__':
        import sys
    
        im=np.random.rand( 2000,5000)
        print('loaded data...')
        if QtGui.QApplication.startingUp():
            app = QtGui.QApplication(sys.argv)
        else:
            app = QtGui.QApplication.instance()
            
        win = DosWindow(im)
        if sys.flags.interactive != 1 :
            app.exec_()

**Comment by almarklein** [comment] 2015-03-27 21:37
confirmed

**Comment by almarklein** [comment] 2015-03-27 21:43
@campagnola can it be that visuals are held onto by the caching mechanism?

**Comment by campagnola** [comment] 2015-03-30 14:06
Looks like this is related to components in ImageVisual; will likely be resolved by #804.

**Comment by almarklein** [comment] 2015-03-30 14:46
@eendebakpt  Also, note that you probably want to use `image.set_data()` for updating your image. Even with the memory leak fixed, the current approach would be slow ...

**Comment by Eric89GXL** [comment] 2015-03-30 22:38
@eendebakpt thanks for the bug report. Here is what I ran:
```Python
import numpy as np
import gc

from vispy import app, visuals
from vispy.visuals.transforms import STTransform, TransformSystem

n_iter = 200


class Canvas(app.Canvas):
    def __init__(self):
        # Create a TransformSystem that will tell the visual how to draw
        super(Canvas, self).__init__(size=(800, 600), keys='interactive')
        image_transform = STTransform(scale=(1, 1), translate=(0, 0))
        tr_sys = TransformSystem(self)
        tr_sys.visual_to_document = image_transform
        self.transform_system = tr_sys
        self.ii = 0
        self.replace_image()
        self.show()

    def replace_image(self):
        newimage = np.random.rand(100, 200, 3)
        self.image = visuals.ImageVisual(newimage, method='subdivide')
        self.ii += 1
        self.update()
        print('reload image')

    def on_draw(self, ev):
        self.context.clear(color='white', depth=True)
        self.context.set_viewport(0, 0, *self.physical_size)
        self.image.draw(self.transform_system)
        self.replace_image()
        gc.collect()
        if self.ii == n_iter:
            self.close()

c = Canvas()
c.app.run()
```
I get this on `master`:

![figure_1](https://cloud.githubusercontent.com/assets/2365790/6908513/e0440c6a-d73d-11e4-91cd-066c658f1382.png)

And a slight improvement but the leak is not eliminated on my PR #804:

![figure_1](https://cloud.githubusercontent.com/assets/2365790/6908531/0e1ab7b0-d73e-11e4-981b-6a7454f5ac9a.png)

I'll keep this in mind while working on that PR.

For future reference, it would be helpful for us if provided minimal examples were as minimal as possible to expose the problem. For example, I didn't have PySide on my system, so I needed to spend time to gut the Qt code and make your example more minimal (above) before I could actually test it. Having less complexity in the example also helps better isolate the issue.

**Closed** 2015-04-05 12:53 UTC
Labels: type: bug, type: performance
