### ISSUE TITLE
Displayed image is rotated 180 degrees.

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#904] opened 2015-05-14 22:04 UTC
When using the `ImageVisual` (with a `PanZoomCamera`) the image is rotated 180 degrees:

![image](https://cloud.githubusercontent.com/assets/99779/7642747/e3f56d58-fa93-11e4-9fc8-951cc5c025c0.png)

It could be coming from the visual or the camera, I haven't checked yet. I don't think the image data is rotated, I have used it in the past straight and this page seems to confirm it is properly oriented: http://sharky93.github.io/docs/gallery/auto_examples/plot_restoration.html

Simplest reproduce case is taking the `vispy.examples.basics.scene.image` module and use Lena:

``` python
# -*- coding: utf-8 -*-
# vispy: gallery 30
# -----------------------------------------------------------------------------
# Copyright (c) 2014, Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# -----------------------------------------------------------------------------
"""
Simple use of SceneCanvas to display an Image.
"""
import sys
from vispy import scene
from vispy import app
import numpy as np

canvas = scene.SceneCanvas(keys='interactive')
canvas.size = 800, 600
canvas.show()

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

# Create the image
# img_data = np.random.normal(size=(100, 100, 3), loc=128,
#                             scale=50).astype(np.ubyte)
import skimage.data
image = scene.visuals.Image(skimage.data.lena(), parent=view.scene)

# Set 2D camera (the camera will scale to the contents in the scene)
view.camera = scene.PanZoomCamera(aspect=1)

if __name__ == '__main__' and sys.flags.interactive == 0:
    app.run()
```

**Comment by campagnola** [comment] 2015-05-15 01:18
The image is flipped vertically (not rotated). The reason is that PanZoomCamera, by default, has its +y axis pointing upward. Image data, on the other hand, is usually represented with its +y axis pointing downward. So you should get the correct results by adding `view.camera.flip = (False, True, False)`.

**Comment by KelSolaar** [comment] 2015-05-15 05:17
Ahh good catch (http://en.wikipedia.org/wiki/Lenna)! Shouldn't the `ImageVisual` be flipped by default otherwise so that all the defaults somehow work properly together?

**Comment by campagnola** [comment] 2015-05-15 13:42
It's not obvious what set of defaults would be the most intuitive for the user. We could:

1. Make ViewBox +y point downward by default. This would be confusing in pretty much every situation except images, so not a good option.
2. Give Image a default STTransform with scaling of (1, -1). As a consequence, all of its children will be vertically flipped as well, which may or may not surprise the user.
3. Have the image render flipped without the use of an external transform. Children would not be flipped, but the user would have to manually flip coordinates if they wanted to map to pixels. 
4. Keep things as they are and flip the view y-axis for high-level functions like `plot.imshow()` 
5. Go back in time and ask the original CRT developers to start scanning from the bottom-left. While we're at it, I'd like the electron to be the positive charge carrier.

**Comment by Eric89GXL** [comment] 2015-05-15 14:01
And just to make things interesting, let's switch to left-handed coordinate systems. :)

@campagnola any idea what children of images might be? I'm not sure what to think of for tha. To me 2 and 3 seem like the best choices from a user perspective, and the use cases for children would help determine which makes more sense. Which do you like?

**Comment by campagnola** [comment] 2015-05-15 14:56
Common children of images might be:

* Arrows (need to have correct access to pixel CS [so 3 is bad], but should not be y-flipped [so 2 is bad]). Imagine you want an arrow pointing to the pixel at row 50, column 30 in an image. How should this be written?

    ```
    image = scene.Image(...)
    image.transform = SomeArbitraryTransform()
    a = scene.Arrow(parent=my_image)
    a.transform.position = (50, 30)  # written exactly as array data would be indexed
    a.transform.position = (30, 50)  # written with x/y transposed, as in view CS
    a.transform.position = (30, my_image.size[1] - 50)  # with y-position manually corrected
    ```
 
* Overlay images (should NOT inherit y-flip from parent)

    ```
    image = scene.Image(...)
    image.transform = SomeArbitraryTransform()
    overlay = scene.Image(..., parent=image)
    ```

* Contour plots (should work correctly regardless of the transformation; no trouble here)

    ```
    image = scene.Image(...)
    image.transform = SomeArbitraryTransform()
    contour = scene.ContourPlot(..., parent=image)
    ```

However the image overlay is a real problem--if you make one image a child of another image, is it obvious that their y-axes will point in opposite directions?

**Comment by campagnola** [comment] 2015-05-15 15:00
Ah, there's a bug here--the documentation for the VisualNodes (http://vispy.readthedocs.org/en/latest/scene.html#module-vispy.scene.visuals) should have included the 'visible' property..

**Comment by almarklein** [comment] 2015-05-28 10:18
My vote would be for option (4): when using `imshow()` we initialize the camera to flip the y-axis.

**Comment by djhoese** [comment] 2019-07-10 22:20
I vote for (4) also. Considering this as a won't fix given how old the issue is and how most people seem to have worked around it except for #1564 which is another issue...

**Closed by djhoese** 2019-07-10 22:20 UTC
