### ISSUE TITLE
black screen with setGeometry

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#1150] opened 2016-01-09 18:22 UTC
The vispy/examples/basics/scene/image.py example works fine on my system (Qt4 backend). However, if I add the line

``` python
canvas.native.setGeometry( 0,0,800,600)
```
to the script I end up with a black screen in the window. After resizing the window manually the image of Mona Lisa appears (as expected). I have tried various commands such as canvas.show(), but with no succes.

**Comment by almarklein** [comment] 2016-03-11 11:35
That's probably because setting the window size in that way does not trigger a vispy resize event. Why not do `canvas.size = 800, 600`?

**Comment by peendebak** [comment] 2016-03-11 22:56
I am on a new system now, so I cannot reproduce the exact same problem. The line

``` python
canvas.native.setGeometry( 0,0,800,600)
```

works for me now, but `canvas.size = 800, 600` (also in combination with `canvas.position=0,0`) gives me a black screen.

I guess these issues are highly dependent on the backend that is being used. I will close the issue.

**Closed** 2016-03-11 22:56 UTC
