### ISSUE TITLE
GridLines appearance in 3D

### ISSUE THREAD

**Issue by ZacDiggum** [vispy/vispy#1399] opened 2017-12-01 11:58 UTC
Hi,
when using a GridLines() scene visual in a 3D view the grid looks, well, really weird. :-)
![screenshot_gridlines](https://user-images.githubusercontent.com/11495528/33481925-f203ae82-d696-11e7-9198-16a946d231b9.png)
I'm using PyQt5 and the latest vispy from the github repo. The grid looks like this both on Windows (10) and Linux (Mint).

**Comment by davidh-ssec** [comment] 2017-12-01 12:15
PyQt5 is not completely supported yet. Could you try making a self-contained example that works with PyQt4 and see how your results change?

**Comment by ZacDiggum** [comment] 2017-12-01 12:23
Ah okay. Will do and post results. Thank you...

**Comment by djhoese** [comment] 2021-11-20 23:53
This is probably a duplicate of #877 and no results have been posted for 4 years. Closing

**Closed by djhoese** 2021-11-20 23:53 UTC
Labels: type: bug
