### ISSUE TITLE
pyqt5 backend bug

### ISSUE THREAD

**Issue by ombschervister** [vispy/vispy#1238] opened 2016-06-16 09:12 UTC
When i use PyQt5 backend, canvas going to be transparent if i draw primitives with alpha channel.

This is in Python 3.4 PyQt5 (incorrect):
![image](https://cloud.githubusercontent.com/assets/3264643/16111320/707bd160-33cb-11e6-8ec0-e6c84a0e6300.png)

This is in Python 2.7 PyQt4 (correct):
![image](https://cloud.githubusercontent.com/assets/3264643/16111330/78d6d45e-33cb-11e6-9e95-fb0493cae5af.png)

Do you have some ideas about this?

``` python
import numpy as np
from vispy import app, gloo

vertex = """
attribute vec3 a_position;
void main (void)
{
    gl_Position = vec4(a_position, 1.0);
}
"""

fragment = """
void main()
{
    gl_FragColor = vec4(1.0, 0.0, 0.0, 0.1);
}
"""

c = app.Canvas()
program = gloo.Program(vertex, fragment)

# gloo.set_state('translucent')
gloo.set_state('opaque')

program['a_position'] = np.array([
    [-1.0, -1.0, 0.0],
    [-1.0, 1.0, 0.0],
    [1.0, -1.0, 0.0],
    [1.0, 1.0, 0.0]
], dtype=np.float32)

@c.connect
def on_resize(event):
    gloo.set_viewport(0, 0, *event.size)

@c.connect
def on_draw(event):
    gloo.clear((0.0, 0.0, 0.0, 1.0))
    program.draw('triangle_strip')

c.show()
app.run()
```

**Comment by ombschervister** [comment] 2016-06-16 13:08
Simple example (full transparent window):

``` python
# -*- coding: utf-8 -*-
import math
from vispy import app, gloo

class Canvas(app.Canvas):
    def __init__(self, *args, **kwargs):
        app.Canvas.__init__(self, *args, **kwargs)

    def on_draw(self, event):
        gloo.clear(color=(0, 0, 0, 0))

if __name__ == '__main__':
    canvas = Canvas()
    canvas.show()
    app.run()
```
![image](https://cloud.githubusercontent.com/assets/3264643/16117778/364e89fc-33ed-11e6-9aaa-bec5b663c8bc.png)

**Comment by ombschervister** [comment] 2016-06-16 13:10
To work around enough to put widget to the MainWindow

**Comment by Eric89GXL** [comment] 2016-10-07 21:18
cc @nfoti you see this too, I think?

**Comment by nfoti** [comment] 2016-10-08 22:36
@Eric89GXL Yes, I see this happen.

**Comment by nfoti** [comment] 2016-10-16 03:54
@Eric89GXL I tried to figure this out today but I'm not very familiar with `PyQt5` nor with `vispy` backends to figure out what @ombschervister was suggesting above.

**Comment by SamiAhola** [comment] 2017-01-24 13:40
I too have the same problem. However, I managed to come up with  a workaround based on the hint by @ombschervister. The workaround is by no means complete, I am happy to just get it working.

original canvas/window creation:
```
canvas = scene.SceneCanvas(show=True, vsync=True, size=(1200, 800-20), position=(2560,20), keys='interactive')
```
workaround:
```
from PyQt5 import QtWidgets
window = QtWidgets.QMainWindow()
window.resize(1200, 800-20) 
window.move(2560, 25)
canvas = scene.SceneCanvas(parent=window, create_native=True, vsync=True, show=True, keys='interactive')
window.setCentralWidget(canvas.native)
window.show()
window.update()
```

Hope this helps.

**Comment by davidh-ssec** [comment] 2017-10-30 14:25
https://github.com/vispy/vispy/issues/1379 is a duplicate of this

**Closed** 2019-03-11 13:50 UTC
