### ISSUE TITLE
Polar Transformation not working for scene.visuals.Image 

### ISSUE THREAD

**Issue by ViNOJ-DAViS** [vispy/vispy#2210] opened 2021-09-03 18:12 UTC
#2133  @kmuehlbauer had demonstrated Polar Transformation for vispy which works perfectly fine with visuals.ImageVisual but when we use scene.visuals.Image it doesn't works as expected.
Please find below sample code which is the modified version of the example shared by @kmuehlbauer.

```
import numpy as np
import vispy.app
from vispy import gloo
from vispy import visuals
from vispy.visuals.transforms import STTransform, PolarTransform, MatrixTransform
from vispy import scene


directions = ["cw", "ccw"]
dir_index = 0

locations = ['N', 'NW', 'W', 'SW', 'S', 'SE', 'E', 'NE']
loc_index = 0

origins = ["top", "bottom"]
ori_index = 0

polar = [True, False]
pol_index = 0

csize = 800

def cycle_state(states, index):
    new_index = (index + 1) % len(states)
    return states[new_index], new_index

class Canvas(vispy.app.Canvas):
    def __init__(self):
        vispy.app.Canvas.__init__(self, keys='interactive', size=(csize, csize))
        # Create image
        xmax = csize // 4
        xres = xmax / 360
        ymax = csize // 2
        yres = ymax / 100

        image = np.ones((xmax, ymax), dtype=np.uint8)
        print(image.shape)

        grad = np.linspace(0, 255, ymax, dtype=np.uint8)[None, :]
        image *= grad

        bl_y1_start, bl_y1_stop = int(yres * 80), int(yres * 90)
        bl_y2_start, bl_y2_stop = int(yres * 95), int(yres * 100)
        wt_y1_start, wt_y1_stop = int(yres * 5), int(yres * 10)
        wt_y2_start, wt_y2_stop = int(yres * 90), int(yres * 95)

        image[:, wt_y1_start:wt_y1_stop] = 255
        image[:, wt_y2_start:wt_y2_stop] = 255
        image[:, bl_y1_start:bl_y1_stop] = 0
        image[:, bl_y2_start:bl_y2_stop] = 0
        image[int(xres*10):int(xres*80)] = 255
        image[int(xres*340):int(xres*350)] = 255

        #self.image = visuals.ImageVisual(image,
        #                                 cmap="grays",
        #                                 grid=(1, 360),
        #                               interpolation="nearest",
        #                                method='subdivide')
        self.image = scene.visuals.Image(image, interpolation="nearest",
                                          cmap="grays", method='subdivide')

        tr1 = (STTransform(scale=(1.0, 1.0, 1), translate=(csize/2, csize/2, 0)))
        self.image.transform = tr1

        self.visuals = [self.image]
        self.title = (f"Direction (d): {directions[dir_index]} - "
                      f"Location (l): {locations[loc_index]} - "
                      f"Origin (o): {origins[ori_index]} - "
                      f"Polar (p): {polar[pol_index]}"
                      )
        self.show()

    def on_draw(self, ev):
        gloo.clear(color='w', depth=True)
        for vis in self.visuals:
            vis.draw()

    def on_resize(self, event):
        # Set canvas viewport and reconfigure visual transforms to match.
        vp = (0, 0, self.physical_size[0], self.physical_size[1])
        self.context.set_viewport(*vp)
        for vis in self.visuals:
            vis.transforms.configure(canvas=self, viewport=vp)

    def on_key_press(self, event):
        global dir_index, loc_index, ori_index, pol_index
        if event.key == 'd':
            dir0, dir_index = cycle_state(directions, dir_index)
        elif event.key == 'l':
            loc0, loc_index = cycle_state(locations, loc_index)
        elif event.key == 'o':
            ori0, ori_index = cycle_state(origins, ori_index)
        elif event.key == "p":
            pol0, pol_index = cycle_state(polar, pol_index)
        else:
            pass

        self.title = (f"Direction (d): {directions[dir_index]} - "
                      f"Location (l): {locations[loc_index]} - "
                      f"Origin (o): {origins[ori_index]} - "
                      f"Polar (p): {polar[pol_index]}")

        # direction
        dir0 = (-1. if directions[dir_index] == 'cw' else 1.)
        # location
        locmap = {
            'N': np.pi * 0.0,
            'NW': np.pi * 0.25,
            'W': np.pi * 0.5,
            'SW': np.pi * 0.75,
            'S': np.pi * 1.0,
            'SE': np.pi * 1.25,
            'E': np.pi * 1.5,
            'NE': np.pi * 1.75}
        loc0 = locmap[locations[loc_index]] / (np.pi * 2)
        # origin
        srcmap = {
            "top": 0,
            "bottom": 1,
        }
        ori0 = srcmap[origins[ori_index]]
        if polar[pol_index]:
            tr = (
                # move image to center and scale
                STTransform(scale=(1.0, 1.0), translate=(400, 400))

                # 0
                # just plain simple polar transform
                * PolarTransform()

                # 1
                # pre scale image to work with polar transform
                # PolarTransform does not work without this
                * STTransform(scale=(2 * np.pi / self.image.size[0], 1.0))

                # 2
                # origin switch via translate.y, fix translate.y
                * STTransform(translate=(self.image.size[0] * (ori0 % 2) * 0.5,
                                         -self.image.size[1] * (ori0 % 2)))

                # 3
                # location change via translate.x
                * STTransform(translate=(self.image.size[0] * (loc0 - 0.25), 0.0))

                # 4
                # direction switch via inverting scale.x
                * STTransform(scale=(dir0, 1.0))
            )
        else:
            tr = (
                STTransform(scale=(1.0, 1.0), translate=(400, 400))

                # origin switch via translate.y, fix translate.y
                * STTransform(translate=(self.image.size[0] * (ori0 % 2) * 0.5,
                                         -self.image.size[1] * (ori0 % 2)))

                # location change via translate.x
                * STTransform(translate=(self.image.size[0] * (loc0 - 0.25), 0.0))

                # direction switch via inverting scale.x
                * STTransform(scale=(dir0, 1.0))
            )

        self.visuals[0].transform = tr
        self.update()


if __name__ == '__main__':
    win = Canvas()
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
```

I tried to put the above program in code tag but it doesn't seem to work.

**Comment by kmuehlbauer** [comment] 2021-09-03 18:15
@ViNOJ-DAViS I can have a look into this next week. Could you show an image in the meantime?

**Comment by ViNOJ-DAViS** [comment] 2021-09-03 18:24
There is no transformation effect at all to the final image
![Screenshot from 2021-09-03 23-51-26](https://user-images.githubusercontent.com/25582939/132050556-4bfa412e-8340-40da-a1d6-509652935b57.png)

**Comment by kmuehlbauer** [comment] 2021-09-06 06:58
@ViNOJ-DAViS I've recreated my original visual example according to the scene image example.

This works nice on my machine, also with Panzoom-Camera

```python
# -*- coding: utf-8 -*-
# vispy: gallery 30
# -----------------------------------------------------------------------------
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# -----------------------------------------------------------------------------
"""
Display an Image
================

Simple use of SceneCanvas to display an Image.

"""

import sys
import numpy as np
from vispy import scene
from vispy import app
from vispy.visuals.transforms import STTransform, PolarTransform

csize = 800
canvas = scene.SceneCanvas(keys='interactive')
canvas.size = csize, csize
canvas.show()

directions = ["cw", "ccw"]
dir_index = 0

locations = ['N', 'NW', 'W', 'SW', 'S', 'SE', 'E', 'NE']
loc_index = 0

origins = ["top", "bottom"]
ori_index = 0

polar = [True, False]
pol_index = 0


def cycle_state(states, index):
    new_index = (index + 1) % len(states)
    return states[new_index], new_index

# Create image
xmax = csize // 4
xres = xmax / 360
ymax = csize // 2
yres = ymax / 100

image_data = np.ones((xmax, ymax), dtype=np.uint8)

grad = np.linspace(0, 255, ymax, dtype=np.uint8)[None, :]
image_data *= grad

bl_y1_start, bl_y1_stop = int(yres * 80), int(yres * 90)
bl_y2_start, bl_y2_stop = int(yres * 95), int(yres * 100)
wt_y1_start, wt_y1_stop = int(yres * 5), int(yres * 10)
wt_y2_start, wt_y2_stop = int(yres * 90), int(yres * 95)

image_data[:, wt_y1_start:wt_y1_stop] = 255
image_data[:, wt_y2_start:wt_y2_stop] = 255
image_data[:, bl_y1_start:bl_y1_stop] = 0
image_data[:, bl_y2_start:bl_y2_stop] = 0
image_data[int(xres * 10):int(xres * 80)] = 255
image_data[int(xres * 340):int(xres * 350)] = 255

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

image = scene.visuals.Image(image_data, interpolation='nearest',
                            grid=(1, 360),
                            parent=view.scene, method='subdivide')

tr1 = (STTransform(scale=(1.0, 1.0, 1), translate=(csize / 2, csize / 2, 0))
       * PolarTransform())

image.transform = tr1

canvas.title = (f"Direction (d): {directions[dir_index]} - "
                f"Location (l): {locations[loc_index]} - "
                f"Origin (o): {origins[ori_index]} - "
                f"Polar (p): {polar[pol_index]}"
                )

# Set 2D camera (the camera will scale to the contents in the scene)
view.camera = scene.PanZoomCamera(rect=(0, 0, csize, csize), aspect=1)
# flip y-axis to have correct aligment
view.camera.flip = (0, 1, 0)


@canvas.events.key_press.connect
def on_key_press(event):
    global dir_index, loc_index, ori_index, pol_index
    if event.key == 'd':
        dir0, dir_index = cycle_state(directions, dir_index)
    elif event.key == 'l':
        loc0, loc_index = cycle_state(locations, loc_index)
    elif event.key == 'o':
        ori0, ori_index = cycle_state(origins, ori_index)
    elif event.key == "p":
        pol0, pol_index = cycle_state(polar, pol_index)
    else:
        pass

    canvas.title = (f"Direction (d): {directions[dir_index]} - "
                    f"Location (l): {locations[loc_index]} - "
                    f"Origin (o): {origins[ori_index]} - "
                    f"Polar (p): {polar[pol_index]}")

    # direction
    dir0 = (-1. if directions[dir_index] == 'cw' else 1.)
    # location
    locmap = {
        'N': np.pi * 0.0,
        'NW': np.pi * 0.25,
        'W': np.pi * 0.5,
        'SW': np.pi * 0.75,
        'S': np.pi * 1.0,
        'SE': np.pi * 1.25,
        'E': np.pi * 1.5,
        'NE': np.pi * 1.75}
    loc0 = locmap[locations[loc_index]] / (np.pi * 2)
    # origin
    srcmap = {
        "top": 0,
        "bottom": 1,
    }
    ori0 = srcmap[origins[ori_index]]

    print("IMAGE_SIZE:", image.size)
    if polar[pol_index]:
        tr = (
                # move image to center and scale
                STTransform(scale=(1.0, 1.0, 1), translate=(csize / 2, csize / 2, 0))

                # 0
                # just plain simple polar transform
                * PolarTransform()

                # 1
                # pre scale image to work with polar transform
                # PolarTransform does not work without this
                # seems, that isn't needed at all with scene
                #* STTransform(scale=(2 * np.pi / image.size[0], 1.0))

                # 2
                # origin switch via translate.y, fix translate.y
                * STTransform(translate=(image.size[0] * (ori0 % 2) * 0.5,
                                         -image.size[1] * (ori0 % 2)))

                # 3
                # location change via translate.x
                * STTransform(translate=(image.size[0] * (loc0 - 0.25), 0.0))

                # 4
                # direction switch via inverting scale.x
                * STTransform(scale=(dir0, 1.0))
        )
    else:
        tr = (
                STTransform(scale=(1.0, 1.0), translate=(400, 400))

                # origin switch via translate.y, fix translate.y
                * STTransform(translate=(image.size[0] * (ori0 % 2) * 0.5,
                                         -image.size[1] * (ori0 % 2)))

                # location change via translate.x
                * STTransform(translate=(image.size[0] * (loc0 - 0.25), 0.0))

                # direction switch via inverting scale.x
                * STTransform(scale=(dir0, 1.0))
        )
    image.transform = tr
    image.update()


if __name__ == '__main__' and sys.flags.interactive == 0:
    app.run()

```

**Comment by ViNOJ-DAViS** [comment] 2021-09-07 08:04
@kmuehlbauer 
Thank you for the update.
But I think the polar transformation and the location part is not working properly.
Please find below image where I have passed same data to our old and new program but the end image is quite different
Do let me know your feedback..
[
![Screenshot from 2021-09-07 13-31-17](https://user-images.githubusercontent.com/25582939/132307956-0628c1b9-e449-4dde-b818-fdce83f46e43.png)
](url)

**Comment by kmuehlbauer** [comment] 2021-09-07 08:12
This looks like the grid-part of the Image is not correctly instantiated. 
```python
image = scene.visuals.Image(image_data, interpolation='nearest',
                            grid=(1, 360), # this one here is needed or needs adapting
                            parent=view.scene, method='subdivide')
```
Obviously there is also some difference in behaviour within the scene or as standalone visual. Hence my comment in number 1 in above code. For me the example in #2133 as well as the above example are working perfectly fine.  Do both examples work for you? Or does only your adapted code not work correctly?

**Comment by ViNOJ-DAViS** [comment] 2021-09-07 11:21
Example from #2133 works fine at my end.
But above example code doesn't seem to work as expected.
Below are couple of the images from the above program from my system.
![Screenshot from 2021-09-07 16-50-57](https://user-images.githubusercontent.com/25582939/132336578-44edaed4-af2b-4bd8-98e6-549834b9ed4e.png)
![Screenshot from 2021-09-07 16-41-34](https://user-images.githubusercontent.com/25582939/132336580-ebc54f8c-80c0-498b-b4cf-f86b18bfd303.png)

**Comment by kmuehlbauer** [comment] 2021-09-07 11:48
@ViNOJ-DAViS  Yes, I can reproduce with my current machine. If I re-enable the commented line (see above, where I changed it) it works again. Could you please check? Will have to see, what happens on my other machine, the next days.

**Comment by ViNOJ-DAViS** [comment] 2021-09-07 12:28
@kmuehlbauer 
In the above example  the grid argument is not commented and same is the case with the program which I am trying in my machine.
I have copy pasted the above example code as it is and it results in above images which I had posted earlier.
Example code of #2133 works perfectly fine though.
Code is as below 
```
image = scene.visuals.Image(image_data, interpolation='nearest',
                            grid=(1, 360),
                            parent=view.scene, method='subdivide'

```

**Comment by ViNOJ-DAViS** [comment] 2021-09-07 12:57
Great! now it works perfectly....
Also I think below change is required for proper location plotting where we add negative to loc0
```
            # 3
            # location change via translate.x
            * STTransform(translate=(image.size[0] * (-loc0 - 0.25), 0.0)
```
Kindly confirm.

Thank you for all the efforts.
Cheers!!

**Comment by kmuehlbauer** [comment] 2021-09-07 13:06
> Also I think below change is required for proper location plotting where we add negative to loc0

Yes, I can confirm! I've changed it in the above example script. Thanks! You might close this issue, if you have no further issues with this.

**Closed** 2021-09-07 13:12 UTC
