### ISSUE TITLE
rolling data gradually became slower

### ISSUE THREAD

**Issue by neurochen** [vispy/vispy#1498] opened 2018-08-01 00:10 UTC
Hello, have anyone seen similar behaviors of roll_data in ScrollingLines and set_data in LinePlot? If I simply call canvas.measure_fps, the reported fps will become smaller and smaller. After around 10 minutes, it dropped from over 60 Hz to 10 Hz. The plots also followed the same trend. I checked the source code for these two functions, without finding the line resulted in this issue. 

My setup is Windows10 x64, python 3.6.5 and vispy 0.5.3. 

Any idea about this issue? This is particularly important for me, as I need to constantly update the figures in at least several hours. Please see below for the code I use, which is a minor-modified version of the sample code in the official package. Thanks.

P.S. There was memory leakages at least for RAM, but not sure with vRAM in the course of getting slower. And just confirmed that the same issue exists in Ubuntu 18.04, python 3.6.5 and vispy 0.5.3 as well.

```python
# -*- coding: utf-8 -*-
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# vispy: gallery 30
"""
Show 10,000 realtime scrolling plots
"""
from vispy import app, scene
import numpy as np


canvas = scene.SceneCanvas(keys='interactive', show=True, size=(1024, 768))
canvas.measure_fps()
grid = canvas.central_widget.add_grid()
view = grid.add_view(0, 1)
view.camera = scene.MagnifyCamera(mag=1, size_factor=0.5, radius_ratio=0.6)

# Add axes
yax = scene.AxisWidget(orientation='left')
yax.stretch = (0.05, 1)
grid.add_widget(yax, 0, 0)
yax.link_view(view)

xax = scene.AxisWidget(orientation='bottom')
xax.stretch = (1, 0.05)
grid.add_widget(xax, 1, 1)
xax.link_view(view)


N = 1
M = 2000
cols = int(N**0.5)
view.camera.rect = (0, 0, cols, N/cols)

lines = scene.ScrollingLines(n_lines=N, line_size=M, columns=cols, dx=0.8/M,
                             cell_size=(1, 8), parent=view.scene)
lines.transform = scene.STTransform(scale=(1, 1/8.))


def update(ev):
    m = 50
    data = np.random.normal(size=(N, m), scale=0.3)
    data[data > 1] += 4
    lines.roll_data(data)

timer = app.Timer(connect=update, interval=0)
timer.start()


if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        app.run()
```

**Comment by djhoese** [comment] 2018-08-01 02:34
Small update: moving the `data` outside of the `update` function and just keep assigning the same data over and over again and the memory usage still goes up. I've also switched to an interval on the timer of `1./60`.

**Comment by djhoese** [comment] 2018-08-01 02:41
Even if I don't set the data on the GPU and just update it I still get increased memory usage and lower FPS:

```python
    def roll_data(self, data):
        """Append new data to the right side of every line strip and remove
        as much data from the left.
        
        Parameters
        ----------
        data : array-like
            A data array to append.
        """
        data = data.astype('float32')[..., np.newaxis]
        s1 = self._data_shape[1] - self._offset
        # if data.shape[1] > s1:
        #     self._pos_tex[:, self._offset:] = data[:, :s1]
        #     self._pos_tex[:, :data.shape[1] - s1] = data[:, s1:]
        #     self._offset = (self._offset + data.shape[1]) % self._data_shape[1]
        # else:
        #     self._pos_tex[:, self._offset:self._offset+data.shape[1]] = data
        #     self._offset += data.shape[1]
        self.shared_program['offset'] = self._offset
        self.update()
```

**Comment by djhoese** [comment] 2018-08-01 02:43
So even commenting out the fps measuring with the above changes to roll_data and I still get increased memory usage. @larsoner @kmuehlbauer What am I missing here?

**Comment by kmuehlbauer** [comment] 2018-08-01 08:03
@djhoese I have only the bad news: Here too the FPS is slowly decreasing. I have no idea where to look atm. But I can say, that this does not happen with a simple TextVisual.

**Comment by neurochen** [comment] 2018-08-01 11:50
Thanks @djhoese @kmuehlbauer for checking this out. One minor update on my side, the same thing happened with set_data with on_mouse_move. Even if I waited for a while after the fps drop, the fps is still at the same low level when I move the mouse again. Based on the tests here, it's definitely caused by set_data or roll_data. And adding a waiting period will not free the resource automatically. As I am not familiar with the internal framework of vispy yet, this seems to require a core developer to come up with a fix. Thanks!

**Comment by neurochen** [comment] 2018-08-01 13:13
Just confirmed @djhoese observation about RAM leakage with a careful check with memory_profiler. It indeed consumed more and more memory after running, which is not supposed to be the case based on the code in set_data.

**Comment by djhoese** [comment] 2018-08-01 13:33
@neurochen Just curious, what version of numpy do you have? What if you try an older version?

**Comment by neurochen** [comment] 2018-08-01 13:53
Interesting idea. Just made a new conda env with numpy 1.7.0, which is released in Feb 2013. I believe that's probably when vispy project began. Still, the same fps drop is observed. See below for the env.

```python
# packages in environment at C:\ProgramFiles\Miniconda3\envs\vispy:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py27_0
icu                       58.2                 h2aa20d9_1
jpeg                      9b                   ha175dff_2
libpng                    1.6.34               h325896a_0
nose                      1.3.7                    py27_2
numpy                     1.7.0                    py27_0
openssl                   1.0.2o               h2c51139_0
pip                       10.0.1                   py27_0
PyOpenGL                  3.1.0                     <pip>
pyqt                      5.6.0            py27h224ed30_5
python                    2.7.15               he216670_0
qt                        5.6.2            vc9hc26998b_12
QtPy                      1.4.2                     <pip>
setuptools                39.2.0                   py27_0
sip                       4.18.1           py27h5ec1c1a_2
sqlite                    3.24.0               h7a46e7a_0
vc                        9                    h7299396_1
vispy                     0.5.3                     <pip>
vs2008_runtime            9.00.30729.1         hfaea7d5_1
vs2015_runtime            15.5.2                        3
wheel                     0.31.1                   py27_0
wincertstore              0.2              py27hf04cefb_0
zlib                      1.2.11               hbc2faf4_2
```

**Comment by codypiersall** [comment] 2018-08-04 04:51
I was looking into this a little bit, and I modified the script to do some profiling with [python-flamegraph](https://github.com/evanhempel/python-flamegraph). (<sub>_Aside: if you're not familiar with flamegraphs, they're a way of visualizing where a program is spending its time.  [Here's the repo](https://github.com/brendangregg/FlameGraph)._</sub>)

Here is the result of running at startup; this is the baseline.  The profiling lasted 10 seconds.
![startup](https://user-images.githubusercontent.com/4684327/43672407-d800a056-9772-11e8-91e9-ea4261b2a361.PNG)

Here is the result of running the program for 1 minute and then profiling for 10 seconds again.
![slow](https://user-images.githubusercontent.com/4684327/43672414-fc47f1e4-9772-11e8-8af0-089183eef809.PNG)

The width of a slice is the wall time that is spent inside a function or a subfunction; the vertical axis is the stack height.  Something funky seems to be going on with [`glTexSubImage2D`](https://github.com/vispy/vispy/blob/6fe28257f56dcbd6c9093ec9b3c1f9f05304bfdb/vispy/gloo/gl/_gl2.py#L1127); at startup it takes about 30% of the run time, but after a minute it takes about 50%.  I'm not sure if that's because it is getting called more often, or if the calls are taking a longer time; I'd guess the latter, but not for any particularly good reason.

This is the code that generates the flamegraphs.  You have to install [`python-flamegraph`](https://github.com/evanhempel/python-flamegraph) to run it, and then [FlameGraph](https://github.com/brendangregg/FlameGraph) to generate the svgs

```python
# -*- coding: utf-8 -*-
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# vispy: gallery 30
"""
Show 10,000 realtime scrolling plots
"""
from vispy import app, scene
import numpy as np
import threading

def prof_thread(prof_time_1=10, wait_time=60, prof_time_2=10):
    """Thread runs in the background and runs a profile at startup and another one after one minute."""
    import flamegraph
    import time
    def format_entry(thread, fname, line, func_name):
        """Format an entry for going into the log"""
        return '{}`{}:{}'.format(thread, fname, func_name)
    # give things time to start up before profiling
    print('letting things start up')
    time.sleep(2)
    print('running first profiling thread')
    fd_short = open('startup.log', 'w', newline='\n')
    # only show entries from the main thread (not this one!)
    filter = 'MainThread'
    thread_short = flamegraph.start_profile_thread(
        fd=fd_short,
        filter=filter,
        format_entry=format_entry,
    )
    time.sleep(prof_time_1)
    thread_short.stop()
    print('Done with the first profile; sleeping a while...')
    for second in range(wait_time, 0, -1):
        print(end='{}\r'.format(second))
        time.sleep(1)

    print('starting 2nd profile thread; dumping to slow.log')
    fd_long = open('slow.log', 'w', newline='\n')
    thread_long = flamegraph.start_profile_thread(
        fd=fd_long,
        filter=filter,
        format_entry=format_entry
    )
    time.sleep(prof_time_2)
    thread_long.stop()
    print('all done!')


canvas = scene.SceneCanvas(keys='interactive', show=True, size=(1024, 768))
canvas.measure_fps()
grid = canvas.central_widget.add_grid()
view = grid.add_view(0, 1)
view.camera = scene.MagnifyCamera(mag=1, size_factor=0.5, radius_ratio=0.6)

# Add axes
yax = scene.AxisWidget(orientation='left')
yax.stretch = (0.05, 1)
grid.add_widget(yax, 0, 0)
yax.link_view(view)

xax = scene.AxisWidget(orientation='bottom')
xax.stretch = (1, 0.05)
grid.add_widget(xax, 1, 1)
xax.link_view(view)


N = 1
M = 2000
cols = int(N**0.5)
view.camera.rect = (0, 0, cols, N/cols)

lines = scene.ScrollingLines(n_lines=N, line_size=M, columns=cols, dx=0.8/M,
                             cell_size=(1, 8), parent=view.scene)
lines.transform = scene.STTransform(scale=(1, 1/8.))


def update(ev):
    m = 50
    data = np.random.normal(size=(N, m), scale=0.3)
    data[data > 1] += 4
    lines.roll_data(data)

timer = app.Timer(connect=update, interval=0)
timer.start()

if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        prof_thread = threading.Thread(target=prof_thread)
        prof_thread.daemon = True
        prof_thread.start()
        app.run()

```

To generate the svgs from the generated logs, run `flamegraph.pl --title "After running for 1 minute" slow.log > slow.svg && flamegraph.pl --title "At startup" startup.log > startup.svg`.

The flamegraph tells you where the program is spending its time -- [glTexSubImage2D](https://github.com/vispy/vispy/blob/6fe28257f56dcbd6c9093ec9b3c1f9f05304bfdb/vispy/gloo/gl/_gl2.py#L1127) -- but doesn't tell us why.  Any ideas?

**Comment by mkubanski** [comment] 2018-08-04 21:33
Hi Guys,

I have been taking a look at this today and have a potential fix (at least it resolved the FPS issue for me). Since I am learning to use git, I have a branch with a committed fix but cant really create a pull request at the moment as it contains another pull request from my master branch which is still open... but you can try it out regardless:

https://github.com/mkubanski/vispy/commit/e55e35d447d47a65211c5304dc01d5e8e1868986

My guess is the memory leak is coming from the solver itself - I have not delved into that....

**Comment by codypiersall** [comment] 2018-08-05 19:43
Nice work @mkubanski!  That works for me too.  I should have noticed in the profiling results that so much time was being spent in `optimize()` after running for a minute, compared with startup!

I guess the problem is that constraints are getting added without getting taken off or something?  That would explain why it slows down (harder to solve the extra constraints) and consumes more memory (more constraints == more memory).

**Comment by neurochen** [comment] 2018-08-06 12:50
Thank you so much @mkubanski! It works on my side too after I install the repo from your branch. Where did you get the 0.6.0dev version? 

@codypiersall Also thank you a lot for your debugging. Visualizing the resources consumed by each function is very helpful! Do you also know some tools to visualize the resources for each variable, even for local variables in functions? That might also be helpful as well.

**Comment by djhoese** [comment] 2018-08-06 13:08
Awesome work everyone! @mkubanski which pull request are you referring too? I see this [one](https://github.com/vispy/vispy/pull/1488) but it isn't based on your master branch.

@larsoner @kmuehlbauer Were you guys aware of any memory/performance issues in the cassowary solver? Is it time we update to a newer version of cassowary or a different library altogether?

**Comment by codypiersall** [comment] 2018-08-06 13:38
Sorry @neurochen, I don't know of any tool like that, but if you find or make one please let me know!

It looks like the [original project](https://github.com/pybee/cassowary) isn't being maintained anymore.  There is a C++ implementation of the same algorithm called [kiwi](https://github.com/nucleic/kiwi) that I haven't used, but which seems promising.  Here's a relevant quote from that repository:

> Kiwi has been designed from the ground up to be lightweight and fast. Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x.

**Comment by djhoese** [comment] 2018-08-06 13:52
@codypiersall Very cool. Kiwi sounds like a good replacement. One issue I see is that there is absolutely no documentation from what I can tell. It is available on conda-forge though so that's good: https://github.com/conda-forge/kiwisolver-feedstock

**Comment by neurochen** [comment] 2018-08-06 14:29
@mkubanski Could you also please take a look at the following code: 

```python
import numpy as np
import vispy.plot as vp

fig = vp.Fig(show=True, bgcolor='gray')
fig.events.key_press.disconnect()
data = np.random.rand(100, 2)
line = fig[0,0].plot(data, symbol='o', width=0, face_color='black', edge_color='white', marker_size=5)

# Legend
texts = ['legend']
colors = ['black']
# put two spacers on top of and on the right side of the legends
grid = fig[0, 0].view.add_grid(margin=0)
spacer = vp.Widget()
spacer.height_max = 10
grid.add_widget(spacer, row=0, col=1)
spacer = vp.Widget()
spacer.width_max = 10
grid.add_widget(spacer, row=1, col=2)
# add legend texts
legend = vp.Widget(bgcolor=None, border_color=None)
legend.width_max = 10
grid.add_widget(legend, row=1, col=1)
legend_grid = legend.add_grid()
labels = [vp.Label(texts[i], color=colors[i], anchor_x='right') for i in range(len(texts))]
for i, label in enumerate(labels):
    label_widget = legend_grid.add_widget(label, row=i, col=0)
    label_widget.height_max = 16

def callback():
    global data, line
    data = np.random.rand(*np.shape(data))
    line.set_data(data, symbol='o', width=0, face_color='black', edge_color='white', marker_size=5)


if __name__ == '__main__':
    from qtpy.QtCore import QTimer
    from qtpy.QtWidgets import QApplication
    app = QApplication([])

    fig.measure_fps()
    timer = QTimer()
    timer.setSingleShot(False)
    timer.timeout.connect(callback)
    timer.start()

    app.exec()
```

Everything works perfectly if we comment out the legend code. But once you add_widget into the legend grid, the fps will be dropped a lot (from 150 to 125). Moreover, the fps will gradually decrease over time as well. I looked into the code related to set_data, without sorting the bugs out. Thanks!

**Comment by codypiersall** [comment] 2018-08-06 15:07
@djhoese The lack of docs is a very good point!  From digging around a bit it looks to me that the solver's main user is [enaml](https://github.com/nucleic/enaml), which is from the same organization.  I couldn't find anything approaching documentation for it.  I did find out that Matplotlib uses it, which is a positive data point to me.  (It was added by [this PR](https://github.com/matplotlib/matplotlib/pull/9082), release note mention it in [2.2.0](https://github.com/matplotlib/matplotlib/releases/tag/v2.2.0)).

**Comment by MatthieuDartiailh** [comment] 2018-08-06 16:31
As one maintainer of both kiwi and enaml I will try to add some docs in the future for kiwi. Not sure when however.

**Comment by kmuehlbauer** [comment] 2018-08-06 16:46
First of all, great work! @djhoese There have been issues with cassowary solver in the past, but not wrt performance. There were problems with the size of different visuals, which changed spuriously. I do not have the issue at hand now, but I can have a look next week.

**Comment by kmuehlbauer** [comment] 2018-08-06 16:50
@djhoese Found it: #1268
@bollu Did you experience performance degradation as reported here?

**Comment by neurochen** [comment] 2018-08-07 00:52
I checked RAM usage for the new version again, as my program finally crashes due to memory issue. Actually, there is still memory leakage and you could clearly see it in the first minute. Right now, the fps will not drop if you have enough memory. But finally, it will crash due to memory leakage.

**Comment by mkubanski** [comment] 2018-08-07 18:05
@neurochen : im on Windows 10 and Python 3.5 too. The 0.6dev version is the current git master (i.e. unreleased). I will take a look at your new version - I assume you are running it on 0.5.3?

@djhoese : Yes it is #1488 which I see you merged now - now I can fix up the way I operate with git and use branches :) I will make a pull request for this grid check in a bit.

**Comment by neurochen** [comment] 2018-08-07 18:06
@mkubanski I am running your github repo version, that is, 0.6.0dev. Thanks!

**Comment by MatthieuDartiailh** [comment] 2018-08-07 18:14
Note that I opened a WIP PR  #1501 about switching from cassowary to kiwi. Anyone feel free to work from it.

**Comment by mkubanski** [comment] 2018-08-07 19:28
@MatthieuDartiailh - I closed my PR as it makes more sense for you to just make the change directly (can you fix up the if statements in your PR?) I was also taking a look at the issue @neurochen mentions and it is an issue with the solver, this time due to the height constraint:

label_widget.height_max = 16

It might be that with your migration that this will be dealt with?

**Comment by neurochen** [comment] 2018-08-09 01:08
@mkubanski Just noticed that my reply to you is not getting posted successfully. I am with Windows 10, python 3.6.5 and you personal repo of vispy. Clearly, you already figure it out. Thanks!

**Comment by kmuehlbauer** [comment] 2019-03-21 13:59
@neurochen Could you please test your application with latest github master (after commit bd14494de960e3b7dfbc377edc10a15a47cd3572) if the slowdown persists?

**Comment by neurochen** [comment] 2019-03-27 00:33
> @neurochen Could you please test your application with latest github master (after commit [bd14494](https://github.com/vispy/vispy/commit/bd14494de960e3b7dfbc377edc10a15a47cd3572)) if the slowdown persists?

Just noticed this message. Already ran the program with the latest github commit of vispy, and there is no memory leakage in both RAM/VRAM and performance drop. Great work! Thanks!

**Comment by djhoese** [comment] 2019-03-27 01:30
Amazing! Thanks @codypiersall!

**Closed by djhoese** 2019-03-27 01:30 UTC

**Comment by kmuehlbauer** [comment] 2019-03-27 05:50
@neurochen As you are on win 10, could I point you to #1609? We are short of WIN 10 testers, so we would really appreciate if you can try the example there on your machine.

**Comment by neurochen** [comment] 2019-03-27 11:52
> @neurochen As you are on win 10, could I point you to #1609? We are short of WIN 10 testers, so we would really appreciate if you can try the example there on your machine.

You are right. I am working on Windows 10 and happy to try the code. Will post the results there. Thanks.
