### ISSUE TITLE
Moduler shaders example has no attribute '_compile'

### ISSUE THREAD

**Issue by stuaxo** [vispy/vispy#1128] opened 2015-11-12 00:07 UTC
This appears in the top right window when I run it

```
Traceback (most recent call last):
  File "sandbox.py", line 594, in update
    exec(code, local, glob)
  File "<string>", line 26, in <module>
AttributeError: 'ModularProgram' object has no attribute '_compile'

```

**Comment by queenish001** [comment] 2021-11-23 10:25
@djhoese

**Comment by djhoese** [comment] 2021-11-23 17:18
If this is still an issue please provide some example code that reproduces it with modern vispy. Given the age of this and the number of changes to vispy since 2015, I'm going to close this but will reopen if you can show that this is still an issue.

**Closed by djhoese** 2021-11-23 17:18 UTC
