### ISSUE TITLE
Functionality test failures

### ISSUE THREAD

**Issue by QuLogic** [vispy/vispy#949] opened 2015-05-30 06:47 UTC
No matter what backend I use, I seem to get (at least) three failures in `test_functionality_desktop`, `test_functionality_proxy`, and `test_functionality_pyopengl`.

```
vispy/gloo/gl/tests/test_functionality.py:39: in test_functionality_desktop
    _test_functonality('gl2')
vispy/gloo/gl/tests/test_functionality.py:89: in _test_functonality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:500: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:540: in _check_result
    assert_equal(pix1, (0, 0, 0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = (32, 32, 32), y = (0, 0, 0), msg = None

    def assert_equal(x, y, msg=None):
        """Backport"""
        if x == y:
            return
        std_msg = '%s not equal to %s' % (_safe_rep(x), _safe_rep(y))
>       raise AssertionError(_format_msg(msg, std_msg))
E       AssertionError: (32, 32, 32) not equal to (0, 0, 0)
```

```
vispy/gloo/gl/tests/test_functionality.py:46: in test_functionality_proxy
    _test_functonality('gl2 debug')
vispy/gloo/gl/tests/test_functionality.py:89: in _test_functonality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:500: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:540: in _check_result
    assert_equal(pix1, (0, 0, 0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = (32, 32, 32), y = (0, 0, 0), msg = None

    def assert_equal(x, y, msg=None):
        """Backport"""
        if x == y:
            return
        std_msg = '%s not equal to %s' % (_safe_rep(x), _safe_rep(y))
>       raise AssertionError(_format_msg(msg, std_msg))
E       AssertionError: (32, 32, 32) not equal to (0, 0, 0)
```

```
/usr/lib64/python3.4/site-packages/numpy/testing/decorators.py:146: in skipper_func
    return f(*args, **kwargs)
vispy/gloo/gl/tests/test_functionality.py:53: in test_functionality_pyopengl
    _test_functonality('pyopengl2')
vispy/gloo/gl/tests/test_functionality.py:89: in _test_functonality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:500: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:540: in _check_result
    assert_equal(pix1, (0, 0, 0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = (32, 32, 32), y = (0, 0, 0), msg = None

    def assert_equal(x, y, msg=None):
        """Backport"""
        if x == y:
            return
        std_msg = '%s not equal to %s' % (_safe_rep(x), _safe_rep(y))
>       raise AssertionError(_format_msg(msg, std_msg))
E       AssertionError: (32, 32, 32) not equal to (0, 0, 0)
```
Running on Intel HD Graphics 4600, Fedora 22.

**Comment by Eric89GXL** [comment] 2015-05-31 02:33
Argh, Intel again... @rossant did you ever figure out how to fix this on your system? I seem to remember you had this problem. Was it on Linux for you as well? I have access to Intel hardware on Windows and it works there. I might be able to get a Linux machine with Intel... @QuLogic do you have time to debug what is happening? Maybe turn the test into some minimal example that you can play with?

**Comment by Eric89GXL** [comment] 2015-05-31 02:35
I have trouble understanding how other more complex GL tests like the visual tests can pass while this one fails, it might be some hint.

**Comment by Eric89GXL** [comment] 2015-05-31 02:35
BTW can you check `vispy.sys_info()` and give the OpenGL version? I don't think it would be the problem in such a simple case, but it's good to know. Please omit the extension list for now.

**Comment by QuLogic** [comment] 2015-05-31 04:30
I can take a look if you have some idea where to look.

```
Platform: Linux-4.0.4-301.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
Python:   3.4.2 (default, Jan 12 2015, 12:13:20)  [GCC 4.9.2 20150107 (Red Hat 4.9.2-5)]
Backend:  PyQt4
pyqt4:    ('PyQt4', '4.11.3', '4.8.6')
pyqt5:    None
pyside:   None
pyglet:   pyglet 1.2.1
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3
_test:    None

GL version:  '3.0 Mesa 10.5.4'
MAX_TEXTURE_SIZE: 8192
```

**Comment by QuLogic** [comment] 2015-05-31 08:34
Oh, looks like this is the same as #649, maybe?

**Comment by Eric89GXL** [comment] 2015-05-31 15:27
Yeah, I'll close this as a duplicate of that one. Please report over there if you figure anything out.

You have OpenGL 3.0, which should be fine for us.

What I'd do is first make a script that does whatever the test does, to isolate it to as few calls as possible. Then I'd try doing things like repeating the commands a few times before checking the result to see if it "takes". If it doesn't, then I'm not 100% sure what else to try, maybe adding some commands that should make it work.

You can also check to see if you get this result on both Pyglet and Qt, which you can check by doing `python make test pyqt4` and `python make test pyglet`. And just to be sure, these are the only failures you get? I'm curious whether the more complex visual tests pass.

**Closed** 2015-05-31 15:27 UTC
