### ISSUE TITLE
test_functionality fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#792] opened 2015-03-26 14:34 UTC
Intel HD Graphics GPU, Python 2.7 and 3.4.

```
(py27)cyrille@gigabyte:~/git/vispy$ py.test vispy/gloo/gl/tests/test_functionality.py
=================================================== test session starts ====================================================
platform linux2 -- Python 2.7.5 -- py-1.4.26 -- pytest-2.6.4
plugins: cov
collected 4 items 

vispy/gloo/gl/tests/test_functionality.py FFFs

========================================================= FAILURES =========================================================
________________________________________________ test_functionality_desktop ________________________________________________

args = (), kwargs = {}

    def skipper_func(*args, **kwargs):
        """Skipper for normal test functions."""
        if skip_val():
            raise nose.SkipTest(get_msg(f, msg))
        else:
>           return f(*args, **kwargs)

/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/numpy/testing/decorators.py:146: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/gloo/gl/tests/test_functionality.py:39: in test_functionality_desktop
    _test_functonality('gl2')
vispy/gloo/gl/tests/test_functionality.py:89: in _test_functonality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:500: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:540: in _check_result
    assert_equal(pix1, (0, 0, 0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = (32, 32, 32), y = (0, 0, 0), msg = None

    def assert_equal(x, y, msg=None):
        """Backport"""
        if x == y:
            return
        std_msg = '%s not equal to %s' % (_safe_rep(x), _safe_rep(y))
>       raise AssertionError(_format_msg(msg, std_msg))
E       AssertionError: (32, 32, 32) not equal to (0, 0, 0)

vispy/testing/_testing.py:105: AssertionError
_________________________________________________ test_functionality_proxy _________________________________________________

args = (), kwargs = {}

    def skipper_func(*args, **kwargs):
        """Skipper for normal test functions."""
        if skip_val():
            raise nose.SkipTest(get_msg(f, msg))
        else:
>           return f(*args, **kwargs)

/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/numpy/testing/decorators.py:146: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/gloo/gl/tests/test_functionality.py:46: in test_functionality_proxy
    _test_functonality('gl2 debug')
vispy/gloo/gl/tests/test_functionality.py:89: in _test_functonality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:500: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:540: in _check_result
    assert_equal(pix1, (0, 0, 0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = (32, 32, 32), y = (0, 0, 0), msg = None

    def assert_equal(x, y, msg=None):
        """Backport"""
        if x == y:
            return
        std_msg = '%s not equal to %s' % (_safe_rep(x), _safe_rep(y))
>       raise AssertionError(_format_msg(msg, std_msg))
E       AssertionError: (32, 32, 32) not equal to (0, 0, 0)

vispy/testing/_testing.py:105: AssertionError
_______________________________________________ test_functionality_pyopengl ________________________________________________

args = (), kwargs = {}

    def skipper_func(*args, **kwargs):
        """Skipper for normal test functions."""
        if skip_val():
            raise nose.SkipTest(get_msg(f, msg))
        else:
>           return f(*args, **kwargs)

/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/numpy/testing/decorators.py:146: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/numpy/testing/decorators.py:146: in skipper_func
    return f(*args, **kwargs)
vispy/gloo/gl/tests/test_functionality.py:53: in test_functionality_pyopengl
    _test_functonality('pyopengl2')
vispy/gloo/gl/tests/test_functionality.py:89: in _test_functonality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:500: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:540: in _check_result
    assert_equal(pix1, (0, 0, 0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = (32, 32, 32), y = (0, 0, 0), msg = None

    def assert_equal(x, y, msg=None):
        """Backport"""
        if x == y:
            return
        std_msg = '%s not equal to %s' % (_safe_rep(x), _safe_rep(y))
>       raise AssertionError(_format_msg(msg, std_msg))
E       AssertionError: (32, 32, 32) not equal to (0, 0, 0)

vispy/testing/_testing.py:105: AssertionError
=========================================== 3 failed, 1 skipped in 1.63 seconds ============================================
```

**Comment by Eric89GXL** [comment] 2015-03-26 14:37
Does this happen for you on `master`?

**Comment by rossant** [comment] 2015-03-26 14:37
This is on my collections PR, which has been rebased off master a couple of hours ago.

I think I've always had this issue on my system.

**Comment by Eric89GXL** [comment] 2015-03-29 20:14
closing as duplicate of #649

**Closed by Eric89GXL** 2015-03-29 20:14 UTC
Labels: type: bug
