### ISSUE TITLE
BaseCamera.set_range() not working for y-dimension

### ISSUE THREAD

**Issue by clarebcook** [vispy/vispy#2017] opened 2021-04-26 16:36 UTC
Hello,
I am using the TurntableCamera to visualize a scene, and I have recently been having trouble with the ```set_range``` function. When the ```x``` range is larger than the ```y``` range, there are no issues, but if ```y``` is larger than ```x```, parts of the desired range start getting cut off. 

For instance, here I called ```set_range(x=(0, 5000), y=(0, 70000))```, and placed ellipses at (0, 8000) and (5000, 62000). As you can see, the ellipses are barely in view. If I place them at (0, 0) and (5000, 70000), they are not visible at all. As the ```y``` range gets larger, the proportion of the range that the ellipses need to be shifted by to be visible in the view also becomes bigger. 

![image](https://user-images.githubusercontent.com/56291702/116118735-dbdf5680-a67a-11eb-8604-5d6d9861273f.png)

Do you have any advice for solving this issue?

Thank you!

**Comment by hmaarrfk** [comment] 2021-04-26 16:56
Are you able to post the code to reproduce this example? it is hard to test and debug without it.

Thanks

**Comment by hmaarrfk** [comment] 2021-04-26 16:57
This blog post can help craft the code you share:
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by clarebcook** [comment] 2021-04-26 19:53
Yes, here is example code:
```
s = scene.SceneCanvas(size=(1024, 512))
view = s.central_widget.add_view()

range_y = (0, 70000)
range_x = (0, 5000)
offset = 15000
view.camera = scene.TurntableCamera(azimuth=0, elevation=-90)
view.camera.set_range(x=range_x, y=range_y)

e1 = scene.Ellipse(center=(range_x[0], range_y[0] + offset), radius=(500, 500),
                               color="red", border_color="red", parent=view.scene)
e2 = scene.Ellipse(center=(range_x[1], range_y[1] - offset), radius=(500, 500),
                               color="blue", border_color="blue", parent=view.scene)
s.show()
```

and the resulting image:
![image](https://user-images.githubusercontent.com/56291702/116141813-6a150600-a696-11eb-8885-f43d10f6f96d.png)

I had to shift the ellipses by 15000 pixels from the supposed corners of the range to get them to appear in the view. I suspect this has something to do with how the scale factor is being calculated from the canvas size. If I initially set the canvas size to (512, 512), there is no issue.

**Comment by djhoese** [comment] 2021-04-26 20:22
A couple things that come to mind:

1. @clarebcook what version of VisPy are you using? A have a faint memory of something being done to a camera since 0.6.x regarding x/y differences. I could be making this up, or it could be a duplicate issue that I can't find right now, or maybe I am actually remembering something. I'd be curious if you get the same results when installing from vispy's github master branch.
2. Do you get similar unexpected behavior when using the pan/zoom camera? The turntable camera may have some odd idea of what a "range" actually represents. I also wouldn't be surprised if you set the ranges separately and did one before the other, if that would change this to the opposite behavior (ex. set the range for y, then set the range for x).

**Comment by clarebcook** [comment] 2021-04-26 20:58
I am using version 0.6.6

I do get the correct behavior from the pan/zoom camera:
![image](https://user-images.githubusercontent.com/56291702/116148865-b106f980-a69e-11eb-8073-b3a0870480c2.png)

I've found a workaround for now by re-setting the scale factor after calling set_range:
```
s = scene.SceneCanvas(size=(1024, 512))
view2 = s.central_widget.add_view()

range_y = (0, 70000)
range_x = (0, 5000)
offset = 0
view2.camera = scene.TurntableCamera(azimuth=0, elevation=-90)
view2.camera.set_range(x=range_x, y=range_y)

e1 = scene.Ellipse(center=(range_x[0], range_y[0] + offset), radius=(500, 500),
                   color="red", border_color="red", parent=view2.scene)
e2 = scene.Ellipse(center=(range_x[1], range_y[1] - offset), radius=(500, 500),
                   color="blue", border_color="blue", parent=view2.scene)

length_x = range_x[1] - range_x[0]
length_y = range_y[1] - range_y[0]
wide_screen = view2.size[0] > view2.size[1]
wide_range = length_x > length_y
if wide_screen == wide_range:
    view2.camera.scale_factor = min(length_x, length_y)
elif wide_screen:
    view2.camera.scale_factor = length_y
else:
    view2.camera.scale_factor = length_x

s.show()
```

**Comment by djhoese** [comment] 2021-04-27 01:05
You may have noticed this already but the turntable camera docstring says:

https://github.com/vispy/vispy/blob/0e98d0f6958941e3d00b31dfc6325161a7eb9949/vispy/scene/cameras/turntable.py#L17-L19

Also this bit of code looks related:

https://github.com/vispy/vispy/blob/0e98d0f6958941e3d00b31dfc6325161a7eb9949/vispy/scene/cameras/perspective.py#L136-L147

I tried adding a ton of print statements to understand what was happening when and I couldn't really come up with anything. I think there is some assumption made in the base "Perspective" class that just doesn't apply to the Turntable class and that messes up what "range" really means.

**Comment by clarebcook** [comment] 2021-04-27 16:15
Ah okay, so I may just need to use ```center``` and ```scale_factor``` instead of ```set_range```. Thank you!

**Comment by djhoese** [comment] 2021-04-27 16:37
If that ends up working for you, let us know. Feel free to close the issue too.

**Closed** 2021-04-27 19:25 UTC
