### ISSUE TITLE
Opening & Loading .OBJ Textures

### ISSUE THREAD

**Issue by infosisio** [vispy/vispy#1683] opened 2019-07-30 02:59 UTC
It is not clear to me at all how to load and apply the textures for an .obj file.

I can see that the read_mesh function accepts a texcoords array but I have no idea what are the associated steps.

Do I have to load and process the .mtl file on my own and process it?

Or is there an option to make the default be automatically pulled and applied, in order to show?

Thanks a lot once again.

**Comment by djhoese** [comment] 2019-07-30 17:16
mtl file loading, that is loading the texture information for an obj or stl file is not yet implemented in vispy. It is meant to be one of the returned values from `read_mesh` but so far will either not exist or will be set to None.

I'm marking this issue as a duplicate of https://github.com/vispy/vispy/issues/1468. Further discussion or progress on this issue should be moved to there. Thanks.

**Closed by djhoese** 2019-07-30 17:16 UTC
