### ISSUE TITLE
opengl version reported incorrectly?

### ISSUE THREAD

**Issue by nilsbecker** [vispy/vispy#1019] opened 2015-07-25 13:42 UTC
I ran some of the demos in the examples/demo directory on my macbook pro running yosemite. i get `WARNING: OpenGL version 3.0 or higher recommended, got 2.1 INTEL-10.6.31. Some functionality may fail.` However according to apple support, https://support.apple.com/en-us/HT202823, this computer should even support OpenGL 4.1

**Comment by almarklein** [comment] 2015-07-25 20:22
This seems to suggest that the Intel driver is in use. Does OS X switch between drivers to balance battery-life and performance?

**Comment by nilsbecker** [comment] 2015-07-25 21:16
I got nothing but intel hardware, Iris 6100. It's a recent 13' retina macbook pro.

**Comment by Eric89GXL** [comment] 2015-07-25 22:57
This has come up before, it's a weird osx thing. I'll have to look for it.
Are you running the qt backend?

**Comment by nilsbecker** [comment] 2015-07-25 23:55
i don't think so. i just ran the examples unchanged, from the terminal, using ipython. also: i use the version of vispy from current anaconda; i copied the examples from github since they did not seem to be installed.

**Comment by Eric89GXL** [comment] 2015-07-26 02:16
Closing as dup of #952, please see and continue discussion there

**Closed by Eric89GXL** 2015-07-26 02:16 UTC

**Comment by Eric89GXL** [comment] 2015-07-26 02:18
BTW, this warning will not be present on current `master`, because we only warn about < OpenGL 2.1 now. The examples are indeed not installed with the package, but they are part of the repo (this is expected behavior).
