### ISSUE TITLE
Improve Jupyter widget performance

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1989] opened 2021-02-12 16:16 UTC
The old SciPy presentation showed some pretty fast visualizations in a jupyter notebook. Granted almost everything about these projects (vispy and jupyter) has changed since then, but computers are faster now so why does something as simple as a rotating cube in a jupyter notebook/lab session fall behind and lag?

* Would a dedicated websocket for GLIR be better?
* Is the javascript code poorly structured/implemented? Very possible since I had to update it with little webgl knowledge so that the widget would work with modern vispy and modern jupyter.
* Is there a faster serialization method that would work to get things between the kernel and the client faster?
* Other ideas that don't involve webassembly or some larger rewrite of an entire system? I'm sure a refactor/rewrite of the vispy.js could be used, but I'd like to find out what's being slow first.

CC @rossant I think you were one of the first people to work on this. If you have ideas I'd love to hear them.

**Comment by djhoese** [comment] 2021-03-15 20:43
See https://github.com/vispy/vispy/issues/134 for a possible approach for better performance.

**Comment by almarklein** [comment] 2021-08-04 09:06
This is now basically a duplicate of https://github.com/vispy/jupyter_rfb/issues/3

**Closed by almarklein** 2021-08-04 09:06 UTC
Labels: component: jupyter-widget-backend, type: enhancement, type: performance
