### ISSUE TITLE
fig.Render() generate noisy image while preview is not.

### ISSUE THREAD

**Issue by elliottzheng** [vispy/vispy#1512] opened 2018-09-05 01:15 UTC
Hey guys, I'm having trouble rendering mesh to an image, the image generated by `fig.Render()` is kinda noisy while the preview is not.  As shown below, the first image is created by `fig.Render()`, and the second is the preview while the `app.run()`. Any idea what causes it?

![rendered](https://user-images.githubusercontent.com/22427645/45065184-5cc43b00-b0ea-11e8-9358-9527d4d009af.png)

![preview](https://user-images.githubusercontent.com/22427645/45065138-140c8200-b0ea-11e8-9355-cb5f7f3febbc.png)

here is my code. I load the `model_000.ply` and render it.
[model_000.zip](https://github.com/vispy/vispy/files/2350805/model_000.zip)

```python
from pointvision.transformation import *
from vispy.geometry import MeshData
from vispy.io.image import write_png
from vispy.plot import Fig
from vispy.scene import visuals
import vispy
import numpy as np
import openmesh as om

def loadply(filepath):
    trimesh = om.read_trimesh(filepath,vertex_color=True,vertex_normal=True)
    coords=trimesh.points()
    colors=trimesh.vertex_colors()[:,:3]
    normals = trimesh.vertex_normals()
    faces=trimesh.face_vertex_indices()
    return coords, colors, normals, faces

def normalize_cloud(coord):
    center = np.mean(coord, axis=0)
    coord = coord - center
    k = np.argmax(coord ** 2)
    max_value = coord[k // 3][k % 3]
    factor = abs(1 / max_value)
    normalized = coord * factor
    return normalized

vertices, colors, normal, triangles= loadply(r'model_000.ply')
vertices=normalize_cloud(vertices)

fig = Fig(size=(512, 512))
plt = fig[0, 0]
plt._configure_3d()


meshdata = MeshData(vertices=vertices, faces=triangles,vertex_colors=colors)
mesh_obj=plt.mesh(meshdata=meshdata,shading='smooth')

mesh_obj.shininess=0
mesh_obj.ambient_light_color=[1,1,1,1]
mesh_obj.shading='smooth'

plt.view.camera.center = (0, 0, 0.75)
plt.view.camera.scale_factor = 2
plt.view.camera.elevation = 0
plt.view.camera.azimuth = 0

img = fig.render() 
write_png('rendered_default.png', img) # which is noisy

if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run() 
```
I‘ m working with windows 10, vispy 0.5.3 , numpy 1.14, matplotlib 2.2.2 ,wxpython 4.0.1

**Comment by djhoese** [comment] 2018-09-05 01:20
Try using the `from vispy.gloo.util import _screenshot` function and see if you get better results. This is on my TODO list for making it public and advertising this function better. We've seen poor results in the past with using render directly.

**Comment by elliottzheng** [comment] 2018-09-05 01:37
@djhoese Thank you for your early reply, but I don't know where to use the `_screenshot()` function, since I read the function comment and it doesn't provide much information, I try to replace the `fig.Render()` with it, but it doesn't work, could you please give me an example? Thanks.

**Comment by djhoese** [comment] 2018-09-05 01:48
You should be able to swap it in for the render call `img = _screenshot()`. The result (`img`) should be a numpy array of RGBA pixels. You should be able to pass that directly to `write_png` from what I can tell. Are you getting an error message?

**Comment by elliottzheng** [comment] 2018-09-05 02:02
@djhoese I didn't get any error message, but the output image is pure black if I use `_screenshot(alpha=False)`, which means the image ndarray is full of 0. I think `_screenshot()` is to take a screenshot from the preview window? Cause when I set `fig.show` to False, the `_screenshot()` returns an image with a different size than `fig.size`.
I try to use it like this
```python
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        img = _screenshot(alpha=False)
        write_png('rendered_default.png', img)
        vispy.app.run()
```
but it didn't work out either, I get the same black image.

**Comment by djhoese** [comment] 2018-09-05 12:50
You may have to draw the figure first before saving the image, but I would have thought this would work. I know there are some people who are doing something very similar to what you are doing. Let me see if I can find the issues they raised.

**Comment by elliottzheng** [comment] 2018-09-10 08:51
@djhoese I rendered the same noisy image with `pyglet` , and I solved it by  enable the depth test in opengl , I guess this issue may be the `vispy` 's render backend doesn't enable the depth test.

**Comment by djhoese** [comment] 2018-09-10 12:35
The depth test being enabled/disabled is set per-visual (because each is its own GL program). There are certain situations where you want depth testing turned off. Have you tried showing the figure then using `_screenshot()`? I don't have time to look deeply in to this issue this week so I can't give you a better solution right now. @larsoner @kmuehlbauer do you guys have any ideas?

**Comment by kmuehlbauer** [comment] 2021-11-04 07:04
Can't reproduce with latest vispy-main branch. Closing. If this reappears, please open an new issue with details.

**Closed by kmuehlbauer** 2021-11-04 07:04 UTC

**Comment by djhoese** [comment] 2021-11-04 13:58
For what it's worth: `fig.render()` uses `SceneCanvas.render` which had some issues with the alpha channel and how it was handled. A couple versions ago this was updated to be more consistent so this may have fixed this.
