### ISSUE TITLE
memory continues increasing when rendering markervisuals to fbo

### ISSUE THREAD

**Issue by ZuchaoWang** [vispy/vispy#724] opened 2015-02-15 01:42 UTC
Hi all,

In the following test code, I try to render one million markervisuals into numpy arrays. I tried it 100 times. Each time I rebuilt the MarkerVisuals object, and I can see that the memory consumption increases drastically, quickly reaching >2G. It also takes over 700ms to render a frame, which I believe is too slow. Can anyone tell me how to stop the memory leak, and how to make the rendering faster?

P.S. I have made this test in win7 and ubuntu 14.04 OS. Besides, I understand that I do not need to rebuilt the MarkerVisuals every time. After all, the positions of visuals are fixed. However, in my real development code, the positions can change. So I rebuild the visuals in my test code.

	from __future__ import print_function, division
	import numpy as np

	from vispy import app, gloo, scene
	from vispy.color import Color, ColorArray, get_colormap
	from vispy.visuals.shaders import ModularProgram, Function
	from vispy.visuals import Visual, MarkersVisual, transforms

	from memory_profiler import profile
	import time

			
	class MyCanvas:
	    def __init__(self):
	        self._canvas = app.Canvas(show=False)
	        self._canvas.show()
	        #self._canvas.show(visible=False)
	        
	    def __del__(self):
	        self.close()
	        
	    def render(self, image_size, world_boundary, visuals, viewport):
	        """
	        Renders a list of visuals to a numpy-array image, with OpenGL.
	        
	        image_size: (width. height)
	        world_boundary: (xmin, xmax, ymin, ymax)
	        visuals: (visual0, visual1, ...), each must be an instance of vispy.visuals.Visual
	        viewport: x, y, w, h; usually: [0,0]+image_size       
	        """
	        tr = transforms.STTransform()
	        coord_world = [[world_boundary[0], world_boundary[2]],
	                       [world_boundary[1], world_boundary[3]]]
	        coord_render = [[0, 0], image_size]
	        tr.set_mapping(coord_world, coord_render)

	        # the following three lines of codes cost less than 0.2 ms
	        # so it is not necessary to keep rendertex and fbo when image_size remains
	        # every time we just ask for new instances
	        rendertex = gloo.Texture2D(format='rgba',shape=(image_size[1],image_size[0],4))
	        fbo = gloo.FrameBuffer(rendertex)
	        self._canvas.size = image_size # this ensures tr_sys is correct
	        
	        im = None
	        with fbo:
	            gloo.set_viewport(*viewport)
	            gloo.clear()
	            tr_sys = transforms.TransformSystem(self._canvas)
	            tr_sys.visual_to_document = tr
	            for visual in visuals:
	                visual.draw(tr_sys)
	            im = fbo.read()
	            
	        return im
	    
	    def close(self):
	        self._canvas.close()
			

	@profile # this decorator print out the memory consumption
	def run_test_once(mycanvas, pos):
		'''
		This function is used for memory and cpu time test
		It performs one pass of points rendering
		
		pos: the points to be render
		mycanvas: the MyCanvas instance used to render the points 
		'''
		points = MarkersVisual()
		points.set_data(pos=pos)
					 
		img_array = mycanvas.render(image_size=[600,600],
	                                world_boundary=[-1,1,-1,1],
	                                visuals=[points],
	                                viewport=[0,0,600,600])
	        
		del points
		
		return img_array
			
			
	if __name__ == '__main__':
		mycanvas = MyCanvas()

		# prepare a 2D point dataset with 1 million points
		n = 1000000
		pos = 0.25 * np.random.randn(n, 2).astype(np.float32)
		
		# run the test 100 times, to test the memeory consumption and cpu time usage
		# each time the 1 million points will be rendered once
		for i in range(100):
			start_time = time.time()
			img_array = run_test_once(mycanvas, pos)
			print("--- %f seconds ---" % (time.time() - start_time))
		
		mycanvas.close()

**Comment by Eric89GXL** [comment] 2015-02-16 23:59
I'm not sure offhand what would be causing the memory increase. Can you try trimming this down to a minimum example? In other words, try to get the bug to show up with the fewest calls necessary. From there, it's easier to isolate particular function calls. For example, it makes it easier to check if rebuilding the objects causes the problem, or if rebuilding plus drawing is necessary, etc. From there we can dig into the `vispy` code to figure out where the problem is.

**Comment by ZuchaoWang** [comment] 2015-02-17 06:59
I've trimmed it down. Now I run the test 5000 times. Each time I execute two function:
  * create_marker_visual creates a MarkerVisual object with 200,000 points
  * draw_marker_visual draws the object I just created

I have defined an 'option' variable with three possible values: 'creation_only', 'drawing_only', 'creation_and_drawing'. By setting different 'option' values, I can test the performance separately. The code are as follows:

	from __future__ import print_function, division
	import numpy as np

	from vispy import app, gloo
	from vispy.visuals import Visual, MarkersVisual, transforms

	import time

	def create_marker_visual(pos):
		myvisual = MarkersVisual()
		myvisual.set_data(pos=pos)
		
		return myvisual

	def draw_marker_visual(mycanvas, myvisual):
		# create a fbo
		rendertex = gloo.Texture2D(format='rgba',shape=(600,600,4))
		fbo = gloo.FrameBuffer(rendertex)
					 
		im = None
		with fbo:
			gloo.set_viewport(0,0,600,600)
			gloo.clear()
			
			# set the transformation
			tr = transforms.STTransform()
			tr.set_mapping([[-1,-1],[1,1]], [[0, 0], [600,600]])
			tr_sys = transforms.TransformSystem(mycanvas)
			tr_sys.visual_to_document = tr
			
			# draw the marker visual to the fbo
			myvisual.draw(tr_sys)
			
			# read the fbo
			im = fbo.read()
			
		fbo.delete()
		rendertex.delete()
			
		return im
			
	if __name__ == '__main__':
		# CHANGE THIS OPTION MANUALLY TO TEST DIFFERENT FUNCTIONS
		option = 'creation_only' # can be 'creation_only', 'drawing_only', 'creation_and_drawing'
		
		# create a canvas
		mycanvas = app.Canvas(size=(600,600))
		mycanvas.show()
		
		# prepare a 2D point dataset with 200k points
		n = 200000
		pos = 0.25 * np.random.randn(n, 2).astype(np.float32)
		
		myvisual = create_marker_visual(pos)
		
		# run the test 5000 times, to test the memory consumption
		# each time the 200k points will be rendered once
		start_time = time.time()
		for i in range(5000):
			if option in ['creation_only','creation_and_drawing']:
				myvisual = create_marker_visual(pos)
			if option in ['drawing_only','creation_and_drawing']:
				im = draw_marker_visual(mycanvas, myvisual)
			if option in ['creation_only','creation_and_drawing']:
				myvisual._program.delete()
				myvisual._vbo.delete()
			print("[--- run no. %d ---]" % i)
		print("--- %f seconds ---" % (time.time() - start_time))
		
		mycanvas.close()
		
I have run them on my Win7 x64 OS, with 6GB memory. Then with the [mprof toolkit](https://pypi.python.org/pypi/memory_profiler), I'm able to plot the run time memory change under different option values. The figure immediately below shows the 'creation_only' case. Now in each loop, I only create a new MarkerVisual object, not drawing them. I can see that the memory is periodically recollected, but there is still considerable memory leak. It takes 117s to finish the 5000 loops.

![test4_creation_only_117s_20150217133101](https://cloud.githubusercontent.com/assets/7141094/6224197/33715d76-b6b3-11e4-98f7-e5397d6f4ad9.png)

The next figure shows the 'drawing_only' case. Now in each loop, I do not create new MarkerVisual object, but draw the old object once. I can see that the memory is constantly increasing, but generally it uses much less memory than MarkerVisual object creation. It takes 390s to finish the 5000 loops.

![test4_drawing_only_390s_20150217132305](https://cloud.githubusercontent.com/assets/7141094/6224260/29e593f2-b6b4-11e4-8dc0-27e03afa8d10.png)

The final figure shows the 'creation_and_drawing' case. Now in each loop, I create a new MarkerVisual object, then draw this new object. I can see that the memory is also recollected periodically, but not completely, as in the 'creation_only' case. Besides, the memory is recollected at a much higher frequency. The memory consumption seems to be larger than the sum of 'creation_only' and 'drawing_only' case. It takes 747s to finish the 5000 loops.

![test4_creation_and_drawing_747s_20150217130611](https://cloud.githubusercontent.com/assets/7141094/6224329/1e233ab4-b6b5-11e4-8ffe-7930e14fe1f1.png)

One thing that should be taken special care of is, for all instances of GLObject, their delete() function should be called manually to release GPU memory. Otherwise there can be GL_OUT_OF_MEMORY errors:

 	fbo.delete()
	rendertex.delete()

	myvisual._program.delete()
	myvisual._vbo.delete()

**Comment by Eric89GXL** [comment] 2015-02-19 05:59
You might be able to clean up the plots a little bit by doing `import gc` and `gc.collect()` to force more frequent garbage collections. But it seems like the trend is there anyway. At the very least it seems like we need to be more careful about how the vbo and programs get freed/deleted when they are replaced, or when their Python counterparts get deleted. I'm not sure if there's an easy fix -- if you have one in mind, a PR is welcome. Otherwise, hopefully we can tackle this in the next month or two.

**Comment by ZuchaoWang** [comment] 2015-02-20 13:22
Hi Eric, currently I cannot find any easy fix. But today I've analyzed the code a little bit, and find several sources of memory leak:

**Source 1**: Circular reference between DataBufferView and VertexBuffer. This is caused by line 250-251 in vispy/gloo/buffer.py, in DataBuffer.\__getitem\__ function:

        view = DataBufferView(self, key)
        self._views.append(view)

**Source 2**: Unknown problems in ModularProgram. An instance of ModularProgram is defined at line 498 of vispy/visuals/markers.py, in MarkersVisual.\__init\__ function:

        self._program = ModularProgram(vert, frag)

After replacing it with gloo.Program, considerable memory are recollected

**Source 3**: Unknown problems in gloo.FrameBufferObject. Below is a test, showing that simply calling "with fbo:" will cause memory leak:

	from __future__ import print_function, division
	import numpy as np

	from vispy import app, gloo
	import gc
			
	if __name__ == '__main__':
		
		# create a canvas
		mycanvas = app.Canvas(size=(600,600))
		mycanvas.show()
		
		# run the test 5000 times to test the memeory consumption
		for i in range(5000):
			gc.collect()
			
			# for each test, I first create a texture and a fbo
			rendertex = gloo.Texture2D(format='rgba',shape=(600,600,4))
			fbo = gloo.FrameBuffer(rendertex)
						 
			# open the fbo and close it immediately
			# the following two lines cause memory leak
			with fbo:
				pass
				
			# delete the texture and fbo
			fbo.delete()
			rendertex.delete()

			print("[--- run no. %d ---]" % i)
		
		# close the canvas
		mycanvas.close()
		
The memory usage plot is as follows:

![test7_20150220205658](https://cloud.githubusercontent.com/assets/7141094/6286774/05b136fa-b946-11e4-9440-5724f14556f0.png)

**Comment by Eric89GXL** [comment] 2015-02-21 11:42
Awesome, thanks for looking into the code a bit. I think I have some fixes for this. PR coming.

**Comment by ZuchaoWang** [comment] 2015-02-21 16:00
Hi Eric, I have tested your fixes with this earlier trimmed test code. It runs perfectly when option = 'creation_only', with no memory leak. When option = 'creation_and_drawing', it improves significantly, but still having memory leak. However, it breaks down when option = 'drawing_only'.

	from __future__ import print_function, division
	import numpy as np

	from vispy import app, gloo
	from vispy.visuals import Visual, MarkersVisual, transforms

	import time

	# CHANGE THIS OPTION MANUALLY TO TEST DIFFERENT FUNCTIONS
	# can be 'creation_only', 'drawing_only', 'creation_and_drawing'
	option = 'creation_and_drawing' 

	def create_marker_visual(pos):
		myvisual = MarkersVisual()
		myvisual.set_data(pos=pos)
		
		return myvisual

	def draw_marker_visual(mycanvas, myvisual):
		# create a fbo
		rendertex = gloo.Texture2D(format='rgba',shape=(600,600,4))
		fbo = gloo.FrameBuffer(rendertex)
					 
		im = None
		with fbo:
			gloo.set_viewport(0,0,600,600)
			gloo.clear()
			
			# set the transformation
			tr = transforms.STTransform()
			tr.set_mapping([[-1,-1],[1,1]], [[0, 0], [600,600]])
			tr_sys = transforms.TransformSystem(mycanvas)
			tr_sys.visual_to_document = tr
			
			# draw the marker visual to the fbo
			myvisual.draw(tr_sys)
			
			# read the fbo
			im = fbo.read()
			
		fbo.delete()
		rendertex.delete()
			
		return im
			
	if __name__ == '__main__':
		
		# create a canvas
		mycanvas = app.Canvas(size=(600,600))
		mycanvas.show()
		
		# prepare a 2D point dataset with 200k points
		n = 200000
		pos = 0.25 * np.random.randn(n, 2).astype(np.float32)
		
		myvisual = create_marker_visual(pos)
		
		# run the test 5000 times, to test the memeory consumption and cpu time usage
		# each time the 200k points will be rendered once
		start_time = time.time()
		for i in range(5000):
			if option in ['creation_only','creation_and_drawing']:
				myvisual = create_marker_visual(pos)
			if option in ['drawing_only','creation_and_drawing']:
				im = draw_marker_visual(mycanvas, myvisual)
			if option in ['creation_only','creation_and_drawing']:
				myvisual._program.delete()
				myvisual._vbo.delete()
			print("[--- run no. %d ---]" % i)
		print("--- %f seconds ---" % (time.time() - start_time))
		
		mycanvas.close()
		
P.S.

Below is the memory usage plot when option = 'creation_only'. No memory leak observed:

![test4_creation_only_133s_20150221232447](https://cloud.githubusercontent.com/assets/7141094/6314672/3edf236e-ba23-11e4-8e97-b6a7b4e0b0b8.png)

When option = 'drawing_only', it breaks down, saying:

	[--- run no. 0 ---]
	Traceback (most recent call last):
	  File "vispy-mem-test4.py", line 65, in <module>
		im = draw_marker_visual(mycanvas, myvisual)
	  File "vispy-mem-test4.py", line 36, in draw_marker_visual
		myvisual.draw(tr_sys)
	  File "C:\Anaconda\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\ma
	rkers.py", line 608, in draw
		self._program.draw('points')
	  File "C:\Anaconda\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\sh
	aders\program.py", line 54, in draw
		self.update_variables()
	  File "C:\Anaconda\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\sh
	aders\program.py", line 79, in update_variables
		name = self.compiler[dep]
	  File "C:\Anaconda\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\sh
	aders\compiler.py", line 46, in __getitem__
		return self._object_names[item]
	KeyError: <Variable "uniform vec4 u_scale" at 0x790a898>

When option = 'creation_and_drawing', it improves significantly, but still having memory leak:

![test4_creation_and_drawing_630s_20150221234554](https://cloud.githubusercontent.com/assets/7141094/6314749/b5e7c87e-ba25-11e4-8cca-3e9e75ed578b.png)

**Comment by almarklein** [comment] 2015-03-26 14:32
Can you please try with latest master? We fixed a lot of memory issues and I suspect this problem is fixed now.

**Comment by Eric89GXL** [comment] 2015-03-26 14:33
I have the script, I can try locally and close if it works.

**Comment by ZuchaoWang** [comment] 2015-03-26 14:35
Thanks for the fix, but I'm quite busy these days. I think Eric will test
that.

2015-03-26 22:32 GMT+08:00 Almar Klein <notifications@github.com>:

> Can you please try with latest master? We fixed a lot of memory issues and
> I suspect this problem is fixed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vispy/vispy/issues/724#issuecomment-86541993>.
>



-- 

王祖超
Zuchao Wang
http://vis.pku.edu.cn/people/zuchaowang
Visualization and Visual Analytics Group
School of Electronic Engineering & Computer Science
Room 2104, Science Building No. 2
Peking University, Beijing 100871, P.R.China

**Comment by Eric89GXL** [comment] 2015-03-26 14:50
Appears to be fixed, feel free to reopen if you experience it again -- and thanks for the reports and test help!

**Closed by Eric89GXL** 2015-03-26 14:50 UTC
Labels: sprint-2015, type: bug, type: performance
