### ISSUE TITLE
Timeline for Development 

### ISSUE THREAD

**Issue by cadop** [vispy/vispy#1045] opened 2015-08-07 00:29 UTC
It would be useful to have a timeline for development so people can know when is a good time to start integrating vispy with their work.  

More specifically in my case, the Getting Started states as item 2:
Scientists without any knowledge of OpenGL, who are seeking a high-level, high-performance plotting toolkit. Use the vispy.plot and vispy.scene interfaces for high-level work (WARNING: experimental / developing code).

For a user as myself, I would come from pyqtgraph, and need to implement a 3D scene with sphere and sticks (lines, or cylinders that can be described similar to a line).  The entire section is listed as experimental, so its hard to know if I start developing with the current code, if the API will change for the scene or sphere methods. 

If the Experimental / Developing code had some timeline in which users could know what items API was set and would not change, and which are planned to be developed in some scale, maybe  <6 months,  <1 year, or > 1 year.  It would be good for 3 months marker as well, but it may become too tiring to update that way.

**Comment by Eric89GXL** [comment] 2015-08-07 01:56
It might be worth adding some rough timelines to the Wiki regarding when we think certain things might solidify (or not). WDYT @campagnola?

**Comment by campagnola** [comment] 2015-08-08 15:41
I would love to have such a thing. I haven't a clue how to make such estimates at this point. Sometimes major issues turn out to have simple solutions, and sometimes minor issues turn into massive overhauls :)
At least we can list the changes we would like to see in rough priority-order. I haven't actually looked at the wiki for a long time, though, probably because it doesn't generate notifications. Maybe it would be better to make a roadmap issue?

**Comment by kmuehlbauer** [comment] 2017-11-06 10:51
@larsoner @davidh-ssec Can be closed? Or do we have to lay out some roadmap?

**Comment by larsoner** [comment] 2017-11-06 11:36
I don't think this will happen due to overhead, so closing for now

**Closed by larsoner** 2017-11-06 11:36 UTC

**Comment by davidh-ssec** [comment] 2017-11-06 13:53
One option would be to use github projects (https://help.github.com/articles/about-project-boards/), but that still requires creating issues/steps to complete the overall task. Right now the issue is that we have so many issues to get through that trying to think about refactoring, optimizing, and finalizing interfaces doesn't make a ton of sense. At least not when it comes to actually completing the work (let's fix issues, not create them).

I agree with closing this, but if someone (user or maintainer) wants to start creating issues to complain about a certain interface I'm ok with that.
