### ISSUE TITLE
PyQt4 and PySide

### ISSUE THREAD

**Issue by ombschervister** [vispy/vispy#1144] opened 2015-12-24 08:48 UTC
My python interpreter has both PySide and PyQT4 libraries simultaneously. When I run my application in debug mode, an exception raises:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5.4\helpers\pydev\pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5.4\helpers\pydev\pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/simple_circle.py", line 55, in <module>
    Canvas(title="Graph").native.show()
  File "D:/simple_circle.py", line 35, in __init__
    **kwargs)
  File "d:\vispy\vispy\app\canvas.py", line 169, in __init__
    self._app = use_app(call_reuse=False)
  File "d:\vispy\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "d:\vispy\vispy\app\application.py", line 49, in __init__
    self._use(backend_name)
  File "d:\vispy\vispy\app\application.py", line 238, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt.
```

It seems running an application from PyCharm in debug mode sys.modules imports both “PySide.QtCore” и “PyQt4.QtCore”. Without debug mode – only “PyQt4.QtCore”, thus the application runs properly.

code:

``` python
import numpy as np
from vispy import gloo, app
from vispy.gloo import set_viewport, set_state, clear

vert = """
void main (void) {
    gl_Position = vec4(a_position,1.0);
    gl_PointSize = 100.0;
}
"""

frag = """
void main()
{
    float r = length(gl_PointCoord - vec2(0.5, 0.5));
    if (r < 0.5)
        gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
    else
        gl_FragColor = vec4(0.0, 1.0, 0.0, 1.0);
}
"""

class Canvas(app.Canvas):

    def __init__(self, **kwargs):
        # Initialize the canvas for real
        app.Canvas.__init__(self, keys='interactive', size=(512, 512),
                            **kwargs)
        self.program = gloo.Program(vert, frag)
        self.program['a_position'] = np.array([[0.3, 0.3, 0.0]], dtype=np.float32)

        set_viewport(0, 0, *self.physical_size)
        set_state(clear_color='white')

        self.show()

    def on_resize(self, event):
        set_viewport(0, 0, *event.physical_size)

    def on_draw(self, event):
        clear(color=True)
        self.program.draw('points')

if __name__ == '__main__':
    import sys
    from PyQt4 import QtGui
    qapp = QtGui.QApplication(sys.argv)
    Canvas(title="Graph").native.show()
    sys.exit(qapp.exec_())
```

**Comment by queenish001** [comment] 2021-11-25 17:46
@djhoese

**Comment by djhoese** [comment] 2021-11-25 19:51
My guess is this is caused by pycharm trying to show some value/property of some other object and it is automatically trying to load all of the backends it can when it shouldn't. That said, this may have been fixed by updates to PyQt4, PySide, PyCharm, or vispy (soooo many variables involved). Given the age of this issue I'm going to close it and if this is still an issue then we can re-open it or create a new one.

**Closed by djhoese** 2021-11-25 19:51 UTC
