### ISSUE TITLE
Serious performance issue in versions 0.9.1/0.9.2

### ISSUE THREAD

**Issue by mars0001** [vispy/vispy#2241] opened 2021-10-23 17:25 UTC
Hello,
Using Windows 10 x64.

I just upgraded the VisPy package and detected a serious performance issue in the application I am working on (FlatCAM beta).
Version 0.9.0 worked fine for me. 
Something changed in 0.9.1 and newer which caused a serious performance drop.

Using the measure_fps() I can see that in the same setup done in FlatCAM:
- using vispy 0.9.0 I get around 50fps
- using vispy 0.9.1 (and 0.9.2) I get around 12fps

Since my app is a CAM application, 12fps is just too low to be usable.
Can someone tell me what changed from 0.9.0 to 0.9.1 and if there is something that can be reverted (by patching or turning off some kind of setting/parameter)?
Thank you!

**Comment by djhoese** [comment] 2021-10-29 18:03
@mars0001 Two things come to mind:

1. The `__update` method should be doing **everything** with numpy arrays. The only time a new numpy array should be created is if new shapes are added and the data has to be expanded. However, even in this case I personally think it would be smarter to pre-allocate a large numpy array and then fill it in with data later in the for loops that follow. If things are already numpy arrays then it may even be possible to avoid the for loops and use slicing/vectorize tricks in numpy to only run a few lines of code instead of doing a for loop. Avoid working with lists unless it is the only thing that makes sense. Bottom line is that if you can reuse the same numpy array then you'll save a ton of time and memory not allocating new arrays or creating temporary numpy arrays. A couple related tricks for that:
   a. If it is likely and common that more shapes will be added then you could allocate the array for larger than you need and then keep a value around for how much of the large array is actually used so you can...
   b. Only pass vispy the data that is filled like `pos=pos_array[:self._num_shapes]`. Subsetting/slicing an array is much faster than creating a new array every time. Numpy should provide vispy with a "view" of the large array and not reallocate the array until it needs it.
2. I always forget how to do it, but I believe `set_data` for these Visuals typically forces a redraw by calling `self.update`. There should be a way in VisPy to "block" this event so that it doesn't do the redraw until later. It may call `.update` on the whole Canvas, but it shouldn't actually draw until later.

**Comment by djhoese** [comment] 2021-10-29 18:05
Related to pre-allocating arrays: `np.empty((rows, cols), dtype=np.float32)` will be the fastest way to create an array that you'll completely fill in later. You could also look into `np.fill` (I think that's what it is) if you wanted to fill the array with a specific value on creation (other than 0 and 1 which have their own functions).

**Comment by mars0001** [comment] 2021-10-29 18:30
Thank you David, I'll see what can be done!

**Comment by djhoese** [comment] 2021-11-20 23:52
Going over some issues. Can this be closed?

**Comment by brisvag** [comment] 2021-11-21 14:35
I think so. We solved the underlying problem, the rest is mostly unrelated. Maybe the `visible` vs `enabled` discussion is worth keeping alive, but that also is mostly cause by a lower lever issue (slowness of the scenegraph with many nodes).

**Comment by djhoese** [comment] 2021-11-21 19:16
If @mars0001 or someone wants to spend a minimal amount of time throwing together a pull request for the `enabled` property because they think it is the best option forward for performance then I'm open to that. We can continue the pros/cons and final implementation details in that PR. But I'd also like to avoid someone spending too much time making it perfect since there will likely be some level of disagreement or other ideas for how it could be implemented.

I'll close this as we've resolved the original issue/discussion/regression.

**Closed by djhoese** 2021-11-21 19:16 UTC

**Comment by mars0001** [comment] 2021-11-22 11:25
> Going over some issues. Can this be closed?

Thank you all for your help in solving this! All OK now.
