### ISSUE TITLE
Mesh visual - shading bug(?)

### ISSUE THREAD

**Issue by lovstakk** [vispy/vispy#1062] opened 2015-08-17 19:01 UTC
Hi, 

I am in the process of moving from Matlab to Python / bumpy, and using vispy for fast visualisation of flow fields. Great work, appreciate the effort! 

I needed to visualise a large amount of tube-like structures, and started to play with the Tube and Mesh visual. Looking at the rendering the shading seems a bit "off", e.g. the junctions become visible through the opaque tube, see image. 

<img width="622" alt="screen shot 2015-08-17 at 20 57 37" src="https://cloud.githubusercontent.com/assets/7841345/9313329/aa98b2de-4522-11e5-8b33-d591823d0d6c.png">

Unfortunately I am a novice in openGL and can't help out. If you have a chance to look at this it would be appreciated. Thanks!

Best Regards,
Lasse Lovstakken

**Comment by rougier** [comment] 2015-08-17 19:44
Can you post the source for the screenshot ? It seems depth testing is disabled and transparency is on. What is the exact color you're using, is there any transparency ?

**Comment by lovstakk** [comment] 2015-08-17 20:54
Sure! I didn't yet alter the gl state, so it should be as for the Mesh Visual: 
```self.set_gl_state('translucent', depth_test=True, cull_face=False)```

The rgba is [1, 0, 0, 1]

Source code: 
-------------------------------------
```python
import sys
from vispy import scene
import numpy as np

canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()

Nt = 1
Nv = 12

points2 = np.zeros([Nt, 3, 4])
vel = np.random.rand(Nt, 3, 3)*10
points2[:, :, 0] = np.random.rand(Nt, 3)*Nt
points2[:, :, 1] = points2[:, :, 0] + vel[:, :, 0]
points2[:, :, 2] = points2[:, :, 1] + vel[:, :, 1]
points2[:, :, 3] = points2[:, :, 2] + vel[:, :, 2]

for k in xrange(points2.shape[0]):
    points = points2[k, :, :].transpose([1, 0])

    l1 = scene.visuals.Tube(points,
                        shading='smooth',
                        color=np.array([1, 0, 0, 1]),
                        tube_points=Nv,
                        mode='triangles')

    view.add(l1)

view.camera = scene.TurntableCamera()
view.camera.set_range((-20, 20), (-20, 20), (-20, 20))
canvas.show()

if __name__ == '__main__':
    if sys.flags.interactive != 1:
        canvas.app.run()
```

**Comment by rougier** [comment] 2015-08-18 06:46
Can you try to set depth testing explicitly ?

**Comment by lovstakk** [comment] 2015-08-18 08:03
I have now tried the exact same code on two different setups:


1)      Macbook Pro with Intel Iris 6100 using OSX, as used when first reporting the issue: Rendering does not look OK, depth testing seems to be missing.

a.       Tried to set depth_test explicitly using gloo. set_state(depth_test=True) at the end of the script, as well as self.set_gl_state(depth_test=True) for every MeshVisual draw call but did not see any effect.

b.      The rendering is however quick, and rotate / zoom functionality works smoothly (see next point)



2)      Desktop with NVidia Titan X on Windows: Depth testing seems to work and rendering looks OK to me!

a.       However, the update rate when rotating / zooming is quite low. Even with just 20 tube objects it starts to lag and also for flat shading.

So some architectural differences are in other words showing up, did you experience this before? Is this working fine on your end?

Lasse

**Comment by rougier** [comment] 2015-08-18 08:32
Maybe a hardware problem on Windows. Are you sure you're accessing the GPU and not emulation through Mesa ?

**Comment by lovstakk** [comment] 2015-08-18 08:46
Hmm, good question. At least Vispy seems to be hardware-accelerated in my other scrips, using the ImageVisual and MarkerVisual, running at 60Hz with many (>2000) markers without any problems with rotating / zooming. Let me know if I can run some specific tests to uncover more.

This is the output from vispy.sys_info()

Platform: Windows-7-6.1.7601-SP1

Python:   2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]

Backend:  PyQt4

pyqt4:    ('PyQt4', '4.10.4', '4.8.6')

pyqt5:    None

pyside:   None

pyglet:   None

glfw:     None

sdl2:     None

wx:       None

egl:      None

_test:    None

GL version:  u'4.5.0 NVIDIA 353.62'

MAX_TEXTURE_SIZE: 16384

Extensions: …

**Comment by rougier** [comment] 2015-08-18 09:12
What about 1 tube only ? Still slow ?

**Comment by lovstakk** [comment] 2015-08-18 09:24
One tube runs just fine, that is, without any noticeable problems. Actually 1-30 tubes runs fine, before a rather sudden slowdown.

**Comment by rougier** [comment] 2015-08-18 09:28
Maybe a cache problem. @campagnola any idea ?

**Comment by campagnola** [comment] 2015-08-22 13:42
I'm not sure what the problem is (you need to profile to be sure), but vispy is not (and perhaps cannot be) optimized for large numbers of visuals. A better approach for you will be to construct a single mesh visual containing all of the geometry you need. If you find the API cumbersome for this, then please do open an issue discussing the API features you'd like to see--this will be a very common use case. I imagine it would not be too difficult to just take a list of mesh visuals like your tubes and automatically generate a single joined mesh..

**Comment by lovstakk** [comment] 2015-08-22 15:52
Thanks for your replies. Indeed I have constructed a joined mesh and this works. This was not the original issue actually, I have an issue with the shader in the MeshVisual on my Macbook pro with Intel Iris 6100 GPU. The depth testing doesn't seem to become activated or something (see image). Works on my desktop with Nvidia GPU.

**Comment by larsoner** [comment] 2017-12-19 15:35
Closing for the summary issue #1345

**Closed by larsoner** 2017-12-19 15:35 UTC
