### ISSUE TITLE
vispy.plot not working in Jupyter notebook

### ISSUE THREAD

**Issue by codypiersall** [vispy/vispy#1312] opened 2017-03-18 02:08 UTC
I cannot get `vispy.plot` to work in a Jupyter notebook.  I'm using the same code as in issue #875:

```
import vispy.app
vispy.app.use_app('ipynb_webgl')
from vispy import plot as vp
fig = vp.Fig(show=False)
fig1 = fig[0, 0]
fig1.plot(range(10000),marker_size=0)
fig.show(run=True)
```

When I run this in a Jupyter notebook, I get a black canvas for a second, then nothing.  The Javascript console contains the following messages:

```
Widget backend and frontend versions are compatible
:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1 Event loop started.
:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1 Event loop stopped.

:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1 Uncaught TypeError: this.glir[n] is not a function
    at n.d.command (:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1)
    at n.d.execute_pending_commands (:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1)
    at n.g.event_tick (:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1)
    at t (:8888/nbextensions/vispy/vispy.min.js?v=20170317210211:1)
```

I'm not getting any Python errors, although I'm getting two issues related to traitlets moving to a toplevel package.  

Python version:

```
(vispy) C:\Users\cody\Dev\vispy>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
Jupyter version:

```
(vispy) C:\Users\cody\Dev\vispy>jupyter notebook --version
4.4.1
```

Vispy is up to date with the GitHub repository.   I'm running this on a Windows 10 box.  Any ideas?

**Comment by codypiersall** [comment] 2017-03-23 01:41
Do you guys think the issue is on the Python side or the JS side?

**Comment by davidh-ssec** [comment] 2017-05-16 21:58
@codypiersall What browsers are you trying this on? Has this ever worked for you? Have you tried older versions of ipython notebook (4.3, 4.2, 4.1)?

**Comment by kmuehlbauer** [comment] 2017-05-19 12:40
@codypiersall @davidh-ssec I can reproduce this. 

Also have a look at [this gist](https://gist.github.com/kmuehlbauer/cd3aeb262c9ceff4ffe554a1a77ac83f)

It seems, that the Widget isn't correctly initialized. At least the error message is suggesting this:

```
self._widget.send_glir_commands(commands)
AttributeError: 'NoneType' object has no attribute 'send_glir_commands'
```

But there might be other parts involved. Anyway, this will be a tough nut to crack. 

My System:
```
"Platform: Linux-4.11.1-1.ga37d575-default-x86_64-with-SuSE-42.2-x86_64
Python:   3.6.1 | packaged by conda-forge | (default, May 11 2017, 17:41:36)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
Backend:  PyQt5\npyqt4:    None\npyqt5:    ('PyQt5', '5.6', '5.6.2')
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3
osmesa:   OSMesa
_test:    None
GL version:  '3.0 Mesa 11.2.2'
```

Conda environment:
```
# packages in environment at /home/kai/miniconda3/envs/vtest:
#
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
dbus                      1.10.10                       3    conda-forge
decorator                 4.0.11                   py36_0    conda-forge
entrypoints               0.2.2                    py36_1    conda-forge
expat                     2.1.0                         2    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
html5lib                  0.999                    py36_0    conda-forge
icu                       58.1                          1    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.0.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.0                    py36_0    conda-forge
jedi                      0.10.0                   py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter_client            5.0.1                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
markupsafe                0.23                     py36_1    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
nbconvert                 5.1.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numpy                     1.12.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2k                        0    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.3                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
prompt_toolkit            1.0.14                   py36_0    conda-forge
ptyprocess                0.5.1                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_2    conda-forge
python                    3.6.1                         2    conda-forge
python-dateutil           2.6.0                    py36_0    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         2    conda-forge
readline                  6.2                           0    conda-forge
setuptools                33.1.1                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3                      py36_0    conda-forge
tk                        8.5.19                        1    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
vispy                     0.5.0.dev0                <pip>
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.2                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by davidh-ssec** [comment] 2017-05-21 21:27
I've started looking in to this and I'm not sure I'm on the right path, but I'll explain what I've found in case it makes something obvious for someone else. My first instinct based on the error message is that this was a bug in the python backend. This brought me to `_ipynb_widget.py`. In this module the canvas and therefore the main widget isn't set on the GLIR parser until `_vispy_set_visible` is called. This is called when `show` is called by the canvas/context. Since show isn't called until your last cell @kmuehlbauer this causes the exception you see. Whether or not this usage should be allowed is another issue, but I was able to get to the next issue by putting all the commands in one cell.

So after moving everything to one cell and executing I start getting javascript errors like `gloo.glir.js:249 Uncaught TypeError: this.glir[method] is not a function`. To help with debugging I cloned the `vispy.js` library and built it myself so I could use the un-minified version. It seems to give the same error either way. If someone could verify that they get this same error that would be great. I also got quite a few errors about vispy.js depending on outdated libraries so we may have to address that too.

Lastly, I investigated why the above error is raised and it looks like the vispy FrameBuffer object is sending the "ATTACH" command with arguments like this ` ["ATTACH", 534, "color", 650]`. However, there is no "attach" method on the javascript `glir` object (see `gloo.glir.js` in `vispy.js`). The thing that is odd to me is that the ATTACH command at least in its current form was added to FrameBuffer in 2014 with f512d9b59f0a77f92f97ff1d453643447770bea2. So I'm guessing I must be doing something wrong with how I'm using this since @Eric89GXL had working examples in #957 in 2015.

It's been a while since I've done javascript so this should be fun.

**Comment by kmuehlbauer** [comment] 2017-05-22 05:48
@davidh-ssec Running all in one cell I get the two ShimWarnings:

```
/home/kai/miniconda3/envs/vtest/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/home/kai/miniconda3/envs/vtest/lib/python3.6/site-packages/vispy-0.5.0.dev0-py3.6.egg/vispy/app/backends/ipython/_widget.py:7: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils.traitlets import Unicode, Int, Bool

/home/kai/miniconda3/envs/vtest/lib/python3.6/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
```

as well as a rate limit warning:

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

When I start the notebook-server with a rather high rate limit:
`jupyter notebook --NotebookApp.iopub_data_rate_limit=2147483647`

I get an JS error message similar to what @codypiersall and @davidh-ssec discovered.
```
07:43:02.485 TypeError: this.glir[n] is not a function 1 vispy.min.js:1:11354
	[4]</d.prototype.command http://localhost:8888/nbextensions/vispy/vispy.min.js:1:11354
	[4]</d.prototype.execute_pending_commands http://localhost:8888/nbextensions/vispy/vispy.min.js:1:11130
	[3]</g.prototype.event_tick http://localhost:8888/nbextensions/vispy/vispy.min.js:1:7346
	t http://localhost:8888/nbextensions/vispy/vispy.min.js:1:1692
```

**Comment by Eric89GXL** [comment] 2017-05-22 13:41
I didn't work on this much so can't be too helpful. However, I'd probably try to go back to a version of VisPy and IPython notebook (I don't even think it was known as Jupyter notebook back then) to see it working, then move VisPy and IPython versions up incrementally to see when it breaks. My guess is that Jupyter API changed at some point.

**Comment by davidh-ssec** [comment] 2017-05-28 15:55
@Eric89GXL @kmuehlbauer I've now spent more time than I think was smart trying to get a working notebook example with vispy. I looked at the vispy and vispy.js commits and found what should have been the used environment that @Eric89GXL said should work, but I could not get it to work in chrome, firefox, or safari. I used a python 3.4 conda environment with ipython 3.0. I tested quite a few different commits of vispy and got a fun number of different results. The commit that I was 90% sure @campagnola was using in #957 causes the ipython kernel to keep restarting. Other commits do weird things like sending a series of commands, but the javascript not receiving every command from the websocket (even though it was part of the same JSON payload). I even fixed some of the shaders in vispy so they wouldn't error out in chrome's webgl compiler due to certain operations not working for certain data type combinations.

There are a few too many variables involved here for debugging the 2015 version of vispy to feel worth it. Javascript libraries change/update, browsers and webgl implementations change, and even if I did get it working it would likely require weird workarounds in vispy that wouldn't even be relevant in the current vispy. Lastly, @Eric89GXL said that that example code "should work" but there isn't any confirmation that it did from @campagnola. I even watched the SciPy 2015 presentation again (I watched it on youtube when it was first presented) and Luke didn't use that plotting example. There were plenty of warnings in that presentation with sentences like: a lot of vispy isn't supported or tested in notebook yet.

So I think any more work on this that I do now will be getting the current vispy to work with the current versions of jupyter notebook. Any other ideas?

**Comment by kmuehlbauer** [comment] 2017-05-29 06:06
@davidh-ssec Same here, tried several old versions of ipython/notebook with several snapshots of vispy with the plot-example to no avail.

Finally I took [the vispy example](https://github.com/ipython-books/cookbook-code/blob/master/notebooks/chapter06_viz/06_vispy.ipynb) from @rossant's cookbook. There I added `app.use_app('ipynb_webgl')` in the import section, to see if the `app`-subsystem actually works and GL-stuff can be displayed in `webgl`.

Besides the ShimWarnings this worked just fine and produced the wanted canvas with the programmed line. 
![vispy_ipynb](https://cloud.githubusercontent.com/assets/5821660/26538184/09d58524-4445-11e7-9091-e1a07f392755.png)
Unfortunately, I didn't had time to investigate further.

FYI: I used latest vispy from github 572158619c04809a26993e808b7af25b2b426ba1 inside a recent conda-forge environment:
[vispy_iypnb.txt](https://github.com/vispy/vispy/files/1034941/vispy_iypnb.txt)

**Comment by davidh-ssec** [comment] 2017-05-29 13:15
@kmuehlbauer Awesome. I was able to get this working too. From what I can tell the higher-level plotting API is the main thing that doesn't work. From what I can tell the main issue is that the plotting API is creating multiple FrameBuffer objects (maybe for swapping?) and these aren't implemented in the vispy.js gloo client. At first glance in the code it doesn't look like multiple frame buffers are created but maybe I'm missing something. I also feel like I've read a discussion from the original maintainers about pros/cons of certain implementations of the plotting framework especially when it comes to webgl/opengl es expectations and performance. @Eric89GXL does this sound familiar at all?

I've just started adding FrameBuffer logic to vispy.js since its a valid webgl object so having the abstraction in the GLIR client won't be a problem. It also won't stop us from changing what the vispy library sends to the client.

**Comment by rossant** [comment] 2017-05-29 13:20
Hello, I'm the one who implemented most of this and it's been a long time since I haven't worked on it. I think you're on the right direction! vispy.js should work as a standalone JS module, there are examples on the vispy.js repo. I never implemented framebuffers in vispy.js but there is no reason why they shouldn't work.

I think the main thing that has completely changed in the IPython API for JS widgets in the notebook. This bit probably has to be rewritten. If you can get vispy.js to work then it shouldn't be too hard.

**Comment by kmuehlbauer** [comment] 2017-05-29 13:36
@davidh-ssec Good that it works for you too.

With a little tweaking I also got the rotating cube visual example running inside a notebook. 

```python
import sys

from vispy import app, gloo
from vispy.visuals import CubeVisual, transforms

class GLCanvas(scene.SceneCanvas):
    def __init__(self):
        scene.SceneCanvas.__init__(self, keys='interactive',
                            size=(400, 400))
        self.unfreeze()
        #app.Canvas.__init__(self, 'Cube', keys='interactive',
        #                    size=(400, 400))

        self.cube = CubeVisual((1.0, 0.5, 0.25), color='red',
                               edge_color="k")
        self.theta = 0
        self.phi = 0

        # Create a TransformSystem that will tell the visual how to draw
        self.cube_transform = transforms.MatrixTransform()
        self.cube.transform = self.cube_transform

        #self._timer = app.Timer('auto', connect=self.on_timer, start=True)

        self.show()

    def on_resize(self, event):
        # Set canvas viewport and reconfigure visual transforms to match.
        vp = (0, 0, self.physical_size[0], self.physical_size[1])
        self.context.set_viewport(*vp)
        self.cube.transforms.configure(canvas=self, viewport=vp)

    def on_draw(self, event):
        gloo.set_viewport(0, 0, *self.physical_size)
        gloo.clear('white', depth=True)

        self.cube.draw()
    
    def on_timer(self, event):
        self.theta += .5
        self.phi += .5
        self.cube_transform.reset()
        self.cube_transform.rotate(self.theta, (0, 0, 1))
        self.cube_transform.rotate(self.phi, (0, 1, 0))
        self.cube_transform.scale((100, 100, 0.001))
        self.cube_transform.translate((200, 200))
        self.update()

win = GLCanvas()

def update(ev):
    win.theta += .5
    win.phi += .5
    win.cube_transform.reset()
    win.cube_transform.rotate(win.theta, (0, 0, 1))
    win.cube_transform.rotate(win.phi, (0, 1, 0))
    win.cube_transform.scale((100, 100, 0.001))
    win.cube_transform.translate((200, 200))
    #win.cube.update()

timer = app.Timer()
timer.connect(win.on_timer)
timer.start(0.025)
app.run()
```

This is the output from the JS-console:
```
Event loop started.  vispy.min.js:1:1786
Error: WebGL: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.  vispy.min.js:1:16212
```

And if you click inside the canvas, then this is displayed:
```
TypeError: o is undefined[Weitere Informationen]  vispy.min.js:1:12820
	[4]</T.prototype.size http://localhost:8888/nbextensions/vispy/vispy.min.js:1:12820
	[4]</d.prototype.command http://localhost:8888/nbextensions/vispy/vispy.min.js:1:11354
	[4]</d.prototype.execute_pending_commands http://localhost:8888/nbextensions/vispy/vispy.min.js:1:11130
	[3]</g.prototype.event_tick http://localhost:8888/nbextensions/vispy/vispy.min.js:1:7346
	t http://localhost:8888/nbextensions/vispy/vispy.min.js:1:1692
```

Unfortunately I'm not that familiar with JS. But if I can help with testing etc. let me know!

**Comment by davidh-ssec** [comment] 2017-05-29 15:54
@kmuehlbauer Interesting. I tried this out and got the same error (after slowing down the timer delay because of bad performance on Chrome). This is the same issue where the python tries to create a FrameBuffer object and then "activate" it, but that object never actually gets created on the javascript side. The FrameBuffer is created during the mouse event because vispy seems to render to a separate FrameBuffer which it then uses to figure out the ID of the visual being clicked on using `SceneCanvas.visual_at`. There is a comment that makes it sound like on IPython this is supposed to raise a RuntimeError and not render off screen, but that doesn't happen with notebook. In fact if you add a `raise RuntimeError()` to line 384 of `scene/canvas.py` in the `visual_at` method you will be able to click and scroll on the webgl canvas. Of course these events don't do anything to the animation, but they don't crash anything then either.

So now I need to figure out what is going on with the plotting interface that is making so many FrameBuffers since it is using the same SceneCanvas.

**Comment by Eric89GXL** [comment] 2017-05-30 13:14
> Got it, every Text object (axes, labels, etc) creates 3 FrameBuffers.

I think this is caused by not sharing a single font manager per context. We didn't make a mechanism for it AFAIK, so it slows things down and creates probably way more things (Textures, FrameBuffers) than is really necessary.

While it's cool that our text code uses SDF (signed distance fields) computed on the GPU, but 1) sometimes this can actually be slow, and 2) sometimes it breaks things. I wonder if we should actually go back to a dumber but more compatible way of loading bitmaps directly using the font library.

**Comment by davidh-ssec** [comment] 2017-06-01 16:48
Just a small update since this is taking longer than I expected given the time I'm putting in to it. I think I have all the framebuffer and related GLIR commands implemented in vispy.js. I've been basing most of my logic off of `vispy/gloo/glir.py` for what commands need to be run when and in what order. The current issue I'm having is that the framebuffers seem to be "INCOMPLETE" even though the texture involved seems to be getting attached and things are getting bound when they should. Wanted to mention this now in case someone knows of some obvious difference between normal opengl and webgl/es. Otherwise I think the next step is to verify that all of the commands in `vispy.js` are operating functionally equivalent to `glir.py`. Now back to paid work...

**Comment by davidh-ssec** [comment] 2017-06-04 02:38
Ok I think this is the last update before I get it all working or at least before I put it in a pull request to be reviewed. Last issue about incomplete attachments was due to the SDF text needing to render to a framebuffer with an attached texture. This was done with no DATA command being sent to "initialize" the texture so I needed to set the data to "null" in the javascript.

Next issue, again with the SDF text rendering, was that it requires the standard derivatives extension. This requires added lines to the javascript and a hack to the python to include extra `#extension` lines to the shaders. Extensions needed were "GL_OES_standard_derivates" and "GL_OES_ext_element_index_uint". @Eric89GXL is there a standard way to define extensions in vispy already? If not, we should probably create an issue to define and discuss a method for this. Although it may only be needed for webgl or es backends. I'm starting to agree with you @Eric89GXL that a simpler text rendering might be needed for easy webgl compatibility and less GLIR processing.

Now I get no errors in running the previous example, however I just get a flickering canvas of black and white and what seems to be an infinite loop of GLIR commands.

**Comment by Eric89GXL** [comment] 2017-06-05 15:09
> This was done with no DATA command being sent to "initialize" the texture so I needed to set the data to "null" in the javascript.

Nice! Sounds like a pain to sort out.

The tragic part is that I had a full working non-SDF version in #317 before moving to SDF, but then I squashed it :( But given the FreeType stuff that's already available and the discussion in that PR, someone could implement an alternative backend.

> @Eric89GXL is there a standard way to define extensions in vispy already?

Not that I recall. You could take a look at the VolumeVisual, I think it requires texture cubes which are only available on some versions of OpenGL. I took a very brief look and didn't see anything.

> I'm starting to agree with you @Eric89GXL that a simpler text rendering might be needed for easy webgl compatibility and less GLIR processing.

Even on high-performance desktops sometimes it ends up being slow. Somehow Qt5 manages to make it work decently, though -- perhaps they don't compute the SDFs on the GPU. If you just stored them for each font it would be much faster and we wouldn't have these issues...

In any case, the best thing I can think of would be to leave the SDF code in the repo, but provide an alternative (to be made default) backend that uses FreeType to render fonts at whatever size necessary. If that's overly complicated, I think that scrapping SDF for now in favor of the simpler method will close more bugs and make things easier in the meantime.

**Comment by rougier** [comment] 2017-06-05 16:08
In glumpy, I compute the SDF on CPU using a [small C extension](https://github.com/glumpy/glumpy/tree/master/glumpy/ext/sdf). From my experience, it's fast enough.

**Comment by Eric89GXL** [comment] 2017-06-05 18:09
> In glumpy, I compute the SDF on CPU using a small C extension.

This makes distribution a bit harder, but might be worth it in this case. There might be other places that would benefit from Cython, too.

**Comment by davidh-ssec** [comment] 2017-06-12 20:48
I did a little more work on figuring out why the "infinite loop" of GLIR commands were being sent to the notebook kernel and I think I at least figured out the cause. In `_ipynb_webgl.py` it implements the `_vispy_update` method by putting a draw callback on the tornado "queue". From what I can understand I think this is putting a callback on the queue for **every** call to `self.update()` that a vispy visual performs. So I think what is happening for our "simple" example is:

1. VisPy objects get created
2. VisPy says "draw"
3. VisPy sub-visuals call `self.update()` which adds 400+ draw callbacks to the tornado queue.
4. Tornado executes the first draw command and everything gets performed as expected.
5. Tornado starts executing the rest of the commands, but since there isn't anything else to do it keeps running the canvas initializing commands. This results in the WebGL buffers getting swapped rapidly. Eventually Tornado finishes running all the callbacks, but you end up with a completely black or white canvas.

I did a terrible hack in the notebook canvas backend to try to say "if we've already added 10 or more callbacks, don't add anymore until one of them is actually called. This got things showing up as expected:
<img width="1115" alt="screen shot 2017-06-12 at 3 33 05 pm" src="https://user-images.githubusercontent.com/1828519/27054220-da3a5938-4f85-11e7-86bf-8da39b401456.png">

Anyone have any ideas how to limit how many callbacks get added to tornado? I'll review this a little more and then make some PRs when I get a chance so people can help me test. I tried to run a few other examples in notebook and all the static ones I tried seem to work. Any examples with animations or mouse/keyboard event handlers seem to have similar issues to the above where you might end up with a black or white canvas instead of the proper things being drawn.

**Comment by Eric89GXL** [comment] 2017-06-12 22:33
Could there be a performance regression even for standard rendering, or
does the queuing work differently there? If 400 scene redraw commands (is
that what's effectively happening?) execute even before the first buffer
flip, that's going to be rough.

**Comment by davidh-ssec** [comment] 2017-06-13 03:38
@Eric89GXL There could be, but it would be a lot harder to "feel" in non-web cases because it's not going through a web socket to the browser and being serialized and deserialized. The 400+ calls to `update` are mainly coming from the TextVisual from what I can tell which makes sense if you look at the code and see that just the `__init__` method results in at least 5 calls to `self.update` and each tick label is a separate TextVisual. You don't see these type of performance problems if you take the basic examples and translate them to notebook; anything that uses `app.Canvas` (you still see the random black/white canvas I think). For example the `line_plot.py` example only results in two Program's being made and 0 calls to `update`.

I'll have to test more examples that don't use text and what kind of performance issues I have. Another time though...

**Comment by Eric89GXL** [comment] 2017-06-13 15:16
> just the __init__ method results in at least 5 calls to self.update and each tick label is a separate TextVisual.
Ahh probably from this sort of thing:
```
        self.color = color
        self.text = text
        self.font_size = font_size
        self.pos = pos
        self.rotation = rotation
```
I wonder if we should add a context manager like:
```
with self.delay_update():
    ...
```
That would check to see if any `self.update()` were called and delay them all until the context manager exits. Then we at least cut this down by a factor of 5, and possibly there would be other savings elsewhere.

> each tick label is a separate TextVisual

This problem would be solved by using a `TextCollection`, but it was never properly integrated into VisPy.  All of the code is already in the repo and/or the Glumpy repo, but someone would need to do the legwork to get it working properly.

**Comment by davidh-ssec** [comment] 2017-06-13 16:35
> I wonder if we should add a context manager

I was curious what the Qt backend was doing for this since PyQt4 is what I use for my project that uses vispy (large tiled satellite images, panning, zooming, etc) because something like redrawing more than once for every small change would probably be a big performance hit. Looks like the Qt backend (`qt.py:QtCanvas`) calls `QWidget.update(self)`. If you read the documentation you find that Qt combines multiple update calls in to one paint event (http://pyqt.sourceforge.net/Docs/PyQt4/qwidget.html#update). Vispy could either implement its own "debouncing" logic or we could require that the backends implement it in some way. The latter makes sense since Qt already implements it, but the former doesn't hurt anything to add it. Perhaps another feature to tack on to 0.6?

Note: I'm also ignoring what seems to be circular update logic where `qt.py:QtCanvas.update` calls `self._canvas.update()` which should result in a `_vispy_update()` which calls `self.update` which is `qt.py:QtCanvas.update` in the first place. Not sure how that isn't happening.

**Comment by davidh-ssec** [comment] 2017-10-04 09:31
It was never officially stated here, but with my PR being merged above the basics of vispy should work fine in a notebook. Issue arise when using mouse events and other higher level features. I do not have a complete list of what doesn't work or what is causing the few things I am seeing, but I'm going to move this issue to milestone 0.6 so we can take it off the checklist for 0.5. My hope is that with a 0.5 release we'll get more eyes on the notebook issues and can hopefully fix all of them and finally close this issue.

**Comment by GeoffBarrett** [comment] 2017-11-06 18:49
I don't seem to be able to use Vispy with the notebook.

I tried the cookbook example that @kmuehlbauer used, however nothing appears. I have the latest version of Vispy and the required dependencies. What does one need to do to properly plot in the notebook? Do I need to install from @davidh-ssec 's forked version  or should the master version be working properly? Do I need to replace the `vispy.js` with a different version? Thanks for the help.

**Comment by davidh-ssec** [comment] 2017-11-06 18:57
@GeoffBarrett All the working code from my fork has been merged in to vispy and is available in the most recent releases of vispy (0.5+). I just ran the rotating cube example that I had on my machine and the only differences were the timer period of `0.1` and most importantly adding the following line right after the `from vispy import app` line:

```
app.use_app('ipynb_webgl')
```

It looks like if you don't include this line it tries to use a Qt or other backend which of course is a *major* issue, but this should at least get you something showing up in your notebook.

**Comment by davidh-ssec** [comment] 2017-11-06 19:22
@larsoner @kmuehlbauer Regarding making the notebook backend load by default if not specified when running in a jupyter notebook kernel I was thinking of adding another if statement here: https://github.com/vispy/vispy/blob/9dbe751dcdbaaa1d17d0a5885f15872b9b0741a8/vispy/app/application.py#L195

That would call `get_ipython()` and check what kind of kernel was running if any (function doesn't exist if not jupyter/ipython kernel). Thoughts?

**Comment by GeoffBarrett** [comment] 2017-11-06 20:09
@davidh-ssec Thanks for the response, I suppose the error my problem has something to do with the following error I get in the terminal.

` 404 GET /static/jupyter-js-widgets.js?v=20171106145118 (::1) 2.00ms referer=http://localhost:8888/notebooks/webgl_example_1.ipynb`

any ideas?

**Comment by davidh-ssec** [comment] 2017-11-06 20:12
Not sure what's in our installation instructions but have you installed jupyter-widgets?

https://github.com/jupyter-widgets/ipywidgets#install

**Comment by larsoner** [comment] 2017-11-06 20:32
I think a conditional for the default when running in `jupyter` is reasonable

**Comment by GeoffBarrett** [comment] 2017-11-06 20:45
@davidh-ssec I followed the instructions on that page as well as those described in Vispy's documentation.

**Comment by GeoffBarrett** [comment] 2017-11-06 21:42
@davidh-ssec can you do me a favor and type in the following code in your rotating cube code?

`print(vispy.sys_info())`

When using the ipynb_webgl backend by using the line `app.use_app('ipynb_webgl')` my output is the following:

`Platform: Windows-10-10.0.15063
Python:   3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
NumPy:    1.13.3
Backend:  ipynb_webgl
pyqt4:    ('PyQt4', '4.11.4', '4.8.7')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''
App info-gathering error:
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\vispy\util\config.py", line 438, in sys_info
    canvas.close()
  File "c:\python34\lib\site-packages\vispy\app\canvas.py", line 457, in close
    self._backend._vispy_close()
  File "c:\python34\lib\site-packages\vispy\app\backends\_ipynb_webgl.py", line 221, in _vispy_close
    raise NotImplementedError()
NotImplementedError
`
Want to see if yours has the same errors.

**Comment by davidh-ssec** [comment] 2017-11-07 00:52
@GeoffBarrett I have this at the top of my module:
```
import sys
import vispy
from vispy import app
app.use_app('ipynb_webgl')
print(vispy.sys_info())
from vispy import scene, gloo
from vispy.visuals import CubeVisual, transforms
```

Results in my kernel crashing so...not good.

**Comment by davidh-ssec** [comment] 2017-11-07 00:58
@GeoffBarrett The issue is that `sys_info()` needs to get a valid context and it then calls `gl` functions directly from the systems `gl` library. I'm very confused at how yours worked at all.

```
        canvas = Canvas('Test', (10, 10), show=False, app=app)
        canvas._backend._vispy_set_current()
        out += 'GL version:  %r\n' % (gl.glGetParameter(gl.GL_VERSION),)
        x_ = gl.GL_MAX_TEXTURE_SIZE
        out += 'MAX_TEXTURE_SIZE: %r\n' % (gl.glGetParameter(x_),)
        out += 'Extensions: %r\n' % (gl.glGetParameter(gl.GL_EXTENSIONS),)
```

**Comment by GeoffBarrett** [comment] 2017-11-08 15:43
@davidh-ssec I am confused as well. I am not sure it really works considering it says `GL version:  ''`, I look in the console while inspecting the page and it says there's an error for jupyter-js-widgets so I am hoping that this is where my problem is. Can I ask what version of ipywidgets you have? I keep getting the following error in my jupyter console:

`404 GET /static/jupyter-js-widgets.js?v=20171108103149 (::1) 8.51ms referer=http://localhost:8888/notebooks/webgl_example_1.ipynb`

I'm hoping if I solve this error, then I'll get the appropriate responses and my kernel would crash when using `sys_info()`

**Comment by davidh-ssec** [comment] 2017-11-08 15:54
```
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.0.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.0                    py36_0    conda-forge
```

**Comment by GeoffBarrett** [comment] 2017-11-08 16:10
@davidh-ssec 

When I switched from the latest version if ipywidgets (ipywidgets-7.0.3) to  ipywidgets-6.0.0, the aforementioned cube code worked.

**Comment by davidh-ssec** [comment] 2017-11-08 17:18
Well that's not good. I guess we'll have to look at the release notes and see what's changed.

**Comment by davidh-ssec** [comment] 2017-11-08 17:26
Yep looks like a lot of changes: http://ipywidgets.readthedocs.io/en/stable/changelog.html#

**Comment by davidh-ssec** [comment] 2017-12-22 20:50
@larsoner Turns out with a new version of ipywidgets my `fix-jupyter-widget` branch seems to be working fine or at least as much as it did before. I have a few changes to fix, but then I think it is ready for a PR. FYI I'm going to drop ipython <3 support. Technically I may be dropping support for older version of ipywidgets too. With the large amount of changes to the ipywidgets expectations for a widget it would be too annoying to try to make it work for both. Plus how many people really stick with older versions of ipython/jupyter when using notebok?

**Comment by larsoner** [comment] 2017-12-23 05:02
Sounds reasonable to me

**Comment by dominikandreas** [comment] 2018-06-30 17:16
hey @larsoner , any updates on this? would love to see this work. I'm also happy to help if you can give me some pointers on where to start

**Comment by larsoner** [comment] 2018-06-30 17:21
I'm not sure what is left to be done

**Comment by dominikandreas** [comment] 2018-06-30 18:06
@djhoese any updates from your end? Couldn't find your fix-jupyter-widget branch, is that pushed somewhere?

**Comment by djhoese** [comment] 2018-06-30 18:41
@dominikandreas Current master should have this all fixed as far as basic vispy visuals and examples. Performance in some areas is still not up to my liking and there are still some things (like volumes) that won't work without modifying the vispy.js code to support fancier webgl functions.

**Comment by djhoese** [comment] 2019-07-08 21:10
This *should* be fixed in current master, although it probably doesn't perform the greatest (limitations of the webgl backend as a whole). I'm closing this given that it *should* work based on my tests. This should work in the next release (0.6).

**Closed by djhoese** 2019-07-08 21:10 UTC
